/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author parsa bahrami
 */

#pragma GCC optimize("O2")

#include <bits/stdc++.h>

using namespace std;

typedef long long int ll;
typedef long double ld;
typedef pair<int, int> pii;
typedef pair<ll, ll> pll;
typedef pair<double, double> pdd;
typedef pair<ld, ld> pld;
typedef pair<string, string> pss;

#define sz(x)                       (ll) x.size()
#define PB(x)                       push_back(x)
#define bs(a, x)                   binary_search(a , a + sizeof(a) / sizeof(a[0] , x)
#define ts(x)                       to_string(x)
#define jjoin(x)                    for (auto i : x) cout << i << endl;
#define all(x)                      (x).begin(),(x).end()
#define bsv(a, x)                  binary_search(all(a), x)
#define Sort(x)                     sort(all((x)))
#define F                           first
#define S                           second
#define Mp                          make_pair
#define tab                         '\t'
#define sep                         ' '
#define error(x)                    cerr << #x << " = " << x << endl
#define fast_io                     ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define file_io                     freopen("in.txt" , "r+" , stdin) ; freopen("out.txt" , "w+" , stdout);
#define set_random                  mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());
#define kill(x)                     return cout << x << endl , 0;
#define endl                        '\n'

inline ll input() {
    ll n;
    cin >> n;
    return n;
}

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 2e5 + 10;
const ll MAXA = 101;
const ll INF = 1e5;
const ll MOD = 1e9 + 7;
const ld PI = 4 * atan((ld) 1);

int main() {
    fast_io;
    set_random;
    ll q;
    cin >> q;
    while (q--) {
        ll n, x = -INF, y = -INF, tmpx = INF, tmpy = INF;
        cin >> n;
        bool chk = 1;
        for (ll i = 0; i < n; i++) {
            ll x1, y1, f1, f2, f3, f4;
            cin >> x1 >> y1 >> f1 >> f2 >> f3 >> f4;
            if (x1 < x && f3 == 0) chk = 0;
            if (x1 > tmpx && f1 == 0) chk = 0;
            if (x1 >= x && x1 <= tmpx) {
                if (f3 == 0) tmpx = x1;
                if (f1 == 0) x = x1;
            }

            if (y1 < y && f2 == 0) chk = 0;
            if (y1 > tmpy && f4 == 0) chk = 0;
            if (y1 >= y && y1 <= tmpy) {
                if (f4 == 0) y = y1;
                if (f2 == 0) tmpy = y1;
            }
        }
        if (chk) {
            cout << chk << " " << x << " " << y << endl;
        } else cout << 0 << endl;

    }
    return 0;
}