#include<cmath>
#include<math.h>
#include<ctype.h>
#include<algorithm>
#include<bitset>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<complex>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<typeinfo>
#include<utility>
#include<valarray>
#include<vector>
#include<string.h>
#include<stdlib.h>
#include<stdio.h>
using namespace std;
int main()
{
 	bool a[120];
 	memset(a,0,sizeof(a));
 	int n,x,y,i,j;
 	cin>>n;
 	cin>>x>>y;
 	for(i=x+1;i<=y;i++)a[i]=1;
 	for(i=2;i<=n;i++){
					  cin>>x>>y;
					  for(j=x+1;j<=y;j++)a[j]=0;
    }
    j=0;
	for(i=1;i<=100;i++)j+=a[i];
	cout<<j<<endl;				  
	//system("pause");
	return 0;
}