#include<cmath>
#include<math.h>
#include<ctype.h>
#include<algorithm>
#include<bitset>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<complex>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<typeinfo>
#include<utility>
#include<valarray>
#include<vector>
#include<string.h>
#include<stdlib.h>
#include<stdio.h>
using namespace std;
int n,m;
int main()
{
 	freopen("input.txt","r",stdin);
 	freopen("output.txt","w",stdout);
 	int i,j,k,l;
 	cin>>n>>m;
 	if(n<=m){
			 for(i=1;i<=n;i++)cout<<"GB";
			 for(i=1;i<=m-n;i++)cout<<"G";
    }
	else{
		 swap(n,m);
		 for(i=1;i<=n;i++)cout<<"BG";
		 for(i=1;i<=m-n;i++)cout<<"B";	
    }
	cout<<endl;	 	 
	//system("pause");
	return 0;
}