#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
/*
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voirega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voirega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voirega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi
rega er traffik spinge i chili d'erba da quanno c'ha 15 anni quindi non scrivete cazzate porco d*o nel mio dm non lo sporcate con le vostre parole stupide brutti bitch ass nigga traffik  il re della trap spinge i chili noi non  che stamo a fa i repperini che se svejamo la mattina e famo i repperini capito questo  trap for real tutte le canzoni che scrivemo sono la nostra vita hai capito gallagher e traffik viviamo in un film er traffik l'hanno arrestato capito perch c'aveva i chili non sapete quanto me mancher stare a casa cor traffik a trapp tutti i giorni in casa sua capito non sapete quanto me mancher er traffik tutte le cose che abbiamo passato le risate tutte le volte che ve avemo preso per il culo a tutti voi


*/
bitset<128> zero,b;
int main(){
    ll t;
    cin >> t;
    while(t--){
        int n; cin >> n;
        b = zero;
        b[0] = 1;
        int s = 0,a;
        while(n--){
            cin >> a;
            s+=a;
            b|=b<<a;
        }
        if(s%2==0 && b[s/2]){
            cout << "YES\n";
        }else{
            cout << "NO\n";
        }
    }
    return 0;
}