#include<cmath>
#include<math.h>
#include<ctype.h>
#include<algorithm>
#include<bitset>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<complex>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<typeinfo>
#include<utility>
#include<valarray>
#include<vector>
#include<string.h>
#include<stdlib.h>
#include<stdio.h>
#define ll   long long
//:
using namespace std;
ll n,res1=1,res2=1,a;
int main()
{
    scanf("%I64d",&n);
    ll t=n;
    a=7;
    while(t){
             if(t&1)res1=(res1*a)%1000000007;
             t>>=1;
             a=(a*a)%1000000007;
    }
    t=n;
    a=27;
    while(t){
             if(t&1)res2=(res2*a)%1000000007;
             t>>=1;
             a=(a*a)%1000000007;
    }
    res2=res2+1000000007-res1;
    res2%=1000000007;
    printf("%I64d\n",res2);
   // system("pause");
    return 0;
}