#include<stdio.h>
int n,w[100001],Q,i,C[100001],a,b,c,j,k;
double P[100001][101],O,S,t1,t2,tt,p1,PP;
int main(){
	scanf("%d",&n);
	for(i=1;i<=n;i++){
		scanf("%d",&w[i]);
		if(w[i]==0)S++;
		P[i][w[i]]=1;
		C[i]=w[i];
	}
	scanf("%d",&Q);
	while(Q--){
		scanf("%d%d%d",&a,&b,&c);
		tt=P[a][0];
		p1=1.0;
		for(i=1;i<=c;i++){
			p1*=(double)(C[a]-i+1)/i;
		}
		for(i=1;i<=w[a];i++){
			PP=P[a][i];
			for(j=1;j<=c&&j<=i;j++){
				if(P[a][i]==0||C[a]-i-c+j+1<=0)continue;
				O=1.0;
				for(k=1;k<=c-j;k++){
					O*=(double)(C[a]-i-k+1)/k;
				}
				for(k=1;k<=j;k++){
					O*=(double)(i-k+1)/k;
				}
				P[a][i]-=O*PP/p1;
				P[a][i-j]+=O*PP/p1;
			}
		}
		S+=P[a][0]-tt;
		C[a]-=c;
		C[b]+=c;
		printf("%.18lf\n",S);
	}
}