#include<cmath>
#include<math.h>
#include<ctype.h>
#include<algorithm>
#include<bitset>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<complex>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<typeinfo>
#include<utility>
#include<valarray>
#include<vector>
#include<string.h>
#include<stdlib.h>
#include<stdio.h>
#include<Windows.h>
using namespace std;
int main()
{
    int n,i,j,k,l;
    cin>>n;
    k=n/2;
    for(i=1;i<=k+1;i++){
                        for(j=1;j<=k+1-i;j++)cout<<'*';
                        for(j=1;j<=2*i-1;j++)cout<<'D';
                        for(j=1;j<=k+1-i;j++)cout<<'*';
                        cout<<endl;
    }
    for(i=1;i<=k;i++){
                      for(j=1;j<=i;j++)cout<<'*';
                      for(j=1;j<=n-2*i;j++)cout<<'D';
                      for(j=1;j<=i;j++)cout<<'*';
                      cout<<endl;
    }
                      
                      
                                          
    //system("pause");
    return 0;
}