#include "bits/stdc++.h"
using namespace std;

typedef string::const_iterator State;
#define eps 1e-8L
#define MAX_MOD 1000000007LL
#define GYAKU 500000004LL
#define MOD 998244353LL
#define pb push_back
#define mp make_pair
typedef long long ll;
typedef long double ld;
#define REP(a, b) for (long long(a) = 0; (a) < (b); ++(a))
#define ALL(x) (x).begin(), (x).end()

#define int long long
vector<vector<pair<int,int>>> vertexs;
void solve()
{
  int n;
  cin >> n;
  vertexs = vector<vector<pair<int, int>>>(n);
  REP(i, n-1)
  {
    int a, b;
    cin >> a >> b;
    a--;
    b--;
    vertexs[a].push_back({b, i});
    vertexs[b].push_back({a, i});
  }
  REP(i,n){
    if(vertexs[i].size() > 2){
      cout << -1 << endl;
      return;
    }
  }
  vector<int> ans(n - 1, -1);
  REP(i, n)
  {
    if(vertexs[i].size() == 1){
      int bobo = 0;
      int now = i;
      int backs = -1;
      while(true){
        int nexts = -1;
        for (auto x : vertexs[now])
        {
          if(x.first == backs){
            continue;
          }
          nexts = x.first;
          ans[x.second] = 2 + bobo;
          bobo ^= 1;
          break;
        }
        if(nexts == -1){
          break;
        }
        backs = now;
        now = nexts;
      }
    }
  }
  REP(i,n-1){
    if(i){
      cout << " ";
    }
    cout << ans[i];
  }
  cout << endl;
}
#undef int

// generated by oj-template v4.7.2
// (https://github.com/online-judge-tools/template-generator)
int main() {
  // Fasterize input/output script
  ios::sync_with_stdio(false);
  cin.tie(nullptr);
  cout << fixed << setprecision(100);
  // scanf/printf user should delete this fasterize input/output script

  int t = 1;
  cin >> t; // comment out if solving multi testcase
  for (int testCase = 1; testCase <= t; ++testCase) {
    solve();
  }
  return 0;
}