/*
....................................................................................................
--------............................................................................................
....................................................................................................
.......................................................---:......---../:...--.......................
..................................................:/osyso:.//:::--::--..............................
.............................................-:/osyhdmdh/-+/ys+/::/+-::.............................
......................................-:+syhhdddddhyydd+.///yhhso+:::-...................---...-----
..................................-:/osydddddhhhhhyNdmo+.://osyyyo/:--.......-----........--...-----
.................--........----:/+osyhdddddddNNNNNdNmyo+://://soysoo//:...-...------....``..........
.......................`.....-:+yhddddhhhhyhddyNNmmmdy++/+//:/:-/so+o++:-.---.``....................
...................````..--:/+sdddddddhyyhddNdNmNdmmho++o+//:.`....:/+//:-..................--....--
.-................---::://+osyddmdmddhyydmmNmNmdmdmmhso++++:`````````.--::..........................
.-..........---:/+oo+/://+oshhddmmmmmmNNNNNNmmdhmmmms++osss/.``````..````...........................
.....-:/++//++oosso++osssyhdmmNNNmmmNNNNNmNmmmdhmmmmysssshhso/:-````..```-.`........................
..-/+syyhysyyyyhhdhsyysydmmmNNmNmmmMMMNNNNNNmmhhdmmdsssssshdNNms-...`.-.`...........................
..-/ssyhyssyhdmdddyhyyyhhdmmmmNmmNNmNNNNmNmmmmdhddmysssssyyyhhy//:-/:..-............................
::+oosyyyyhhhddhyyhhyyysyhhdmNmmmNmmmmNNmdmdddddhhhsysssssyys+oo+/::s+-::-.-........................
.::/+sssssyhddddddhhhhhhddmmmdddNmmmNNNddmmddhdddhhhyssssssyy+:+s+/::oo/++:..............-..........
.`.-+ossyhdddhddhyyyhdddddmdddmNdmmNMmhdddhhyhhhdhhssossssssyy/:yys//:oo+o+:...-....................
``.:++osyhhhhhhyosyydmNNNmhhhdmmmmdmddddhhyyyyyhhhhysossyyysyhhsyhhyo++oso++-...................---.
``-://+oosyyyyhhdhhhdddhyyyhmNdddhmddhhyyyyysyyhhhddyssyyyyyyyyyyyyhhysosyo//-......................
`.-//+++++++ooso+ooyhhyyyhdmmhyyyhhhyyysssssssyyhhdddysyhhhhdhhhhhyhyhyoooo+::-------.......-------.
.-::::/+ooooooooosyhhhhhhhhhhyyyhyyyssssoosssssyyhhddhs+yddmmddddddhhhhyhs+//:----..----....---.....
```````..---:://///+ooso+ossyssyyssssoooooooosssyyhhho-..--:/ohddmdmddddys///:--........-...--......
```````````````.--.../+/++oooosooooooooooooooossyyyy+......----/shmddmmd+oo//:--...........-------..
````````````````..```....-:++ooooooo+ooooooooosssso:............../ydhdh/MNs////...............--...
`````````````````..```.```:++++++++++++oooooossso+-.................ydhh+odh+++-....................
``````````````````..``..``.-/////////++oooooooo+:....-..............+hddhhso+-......................
``````````````````````...``````://////++oooooo/......-............-.-:+sso/--.......................
```````````````````````.-.`````.://///+++++++-.--..........................-::::-..-................
```````````````````````....`````-:////++/++:....................`..........--.......................
````````..````````..````...``````:////////-.....................................-...................
 ```````..`````````````..````````-/////::-...............-::-...........................-...........
*/

#include <iostream>

using namespace std;

int main()
{
  int n;
  cin >> n;
  cout << n << '\n';
  for(int i = 1 ; i <= n ; i++)
    cout << 1 << " ";

  return 0;
}