#include<stdio.h>
using namespace std;
int a[255][255];
int verif(int i,int j){
    int l1,l2,x,y,pp,k;
    if(a[i][j]==1&&a[i+1][j]==1&&a[i][j+1]==1&&a[i+1][j+1]==1)
        if(a[i-1][j-1]==0&&a[i-1][j]==0&&a[i-1][j+1]==0&&a[i-1][j+2]==0&&a[i][j-1]==0&&a[i+1][j-1]==0&&a[i+2][j-1]==0&&a[i+2][j]==0&&a[i+2][j+1]==0&&a[i+2][j+2]==0&&a[i+1][j+2]==0&&a[i][j+2]==0)
            return 1;
    if(a[i-1][j]==0&&a[i][j-1]==0&&a[i-1][j-1]==0){
        l1=1;
        x=i;
        y=j+1;
        while(a[x][y]==1&&a[x-1][y]==0&&a[x+1][y]==0){
            y++;
            l1++;
        }
        if(a[x][y]!=0&&a[x-1][y]==0&&a[x][y+1]==0&&a[x-1][y+1]==0&&a[x+1][y+1]==0&&a[x+1][y-1]==0){
            l1++;
            l2=1;
            x++;
            while(a[x][y]==1&&a[x][y+1]==0&&a[x][y-1]==0){
                x++;
                l2++;
            }
            if(a[x][y]==1&&a[x][y+1]==0&&a[x+1][y]==0&&a[x+1][y-1]==0&&a[x+1][y+1]==0){
                l2++;
                if(l1==l2){
                    pp=0;
                    y--;
                    for(k=1;k<=l2-2&&pp==0;k++)
                        if(a[x][y]!=1||a[x-1][y]==1||a[x+1][y]==1)
                            pp=1;
                        else
                            y--;
                    if(pp==0&&a[x][y]==1&&a[x+1][y]==0&&a[x][y-1]==0&&a[x+1][y-1]==0&&a[x-1][y-1]==0){
                        pp=0;
                        x--;
                        for(k=1;k<=l2-2&&pp==0;k++)
                            if(a[x][y]!=1||a[x][y-1]==1||a[x][y+1]==1)
                                pp=1;
                            else
                                x--;
                        if(pp==0)
                            return 1;
                    }
                }
            }
        }
    }
    if(a[i][j-1]==0&&a[i-1][j-1]==0&&a[i-1][j]==0&&a[i-1][j+1]==0){
        l1=1;
        x=i+1;
        y=j+1;
        while(a[x][y]==1&&a[x-1][y]==0&&a[x-1][y+1]==0&&a[x][y-1]==0&&a[x+1][y-1]==0){
            x++;
            y++;
            l1++;
        }
        if(a[x][y]==1&&a[x][y-1]==0&&a[x-1][y]==0&&a[x-1][y+1]==0&&a[x][y+1]==0&&a[x+1][y+1]==0&&a[x+1][y]==0){
            l1++;
            l2=1;
            x++;
            y--;
            while(a[x][y]==1&&a[x][y+1]==0&&a[x][y-1]==0&&a[x+1][y+1]==0&&a[x-1][y-1]==0){
                x++;
                y--;
                l2++;
            }
            if(a[x][y]==1&&a[x+1][y+1]==0&&a[x][y+1]==0&&a[x][y-1]==0&&a[x+1][y]==0&&a[x-1][y]==0&&a[x+1][y-1]==0){
                l2++;
                if(l1==l2){
                    pp=0;
                    y--;
                    x--;
                    for(k=1;k<=l1-2&&pp==0;k++)
                        if(a[x][y]==0||a[x][y+1]==1||a[x][y-1]==1||a[x+1][y-1]==1||a[x-1][y+1]==1)
                            pp=1;
                        else{
                            y--;
                            x--;
                        }
                    if(pp==0&&a[x][y]==1&&a[x][y+1]==0&&a[x][y-1]==0&&a[x-1][y]==0&&a[x-1][y-1]==0&&a[x+1][y-1]==0){
                        pp=0;
                        x--;
                        y++;
                        for(k=1;k<=l1-2&&pp==0;k++)
                            if(a[x][y]==0||a[x][y-1]==1||a[x][y+1]==1||a[x-1][y-1]==1||a[x+1][y+1]==1)
                                pp=1;
                            else{
                                x--;
                                y++;
                            }
                        if(pp==0)
                            return 1;
                    }
                }
            }
        }
    }
    return 0;
}
int main(){
    //freopen("tema.in","r",stdin);
    //freopen("tema.out","w",stdout);
    int t,q,i,j,m,n,nr;
    char c;
    scanf("%d",&t);
    for(q=1;q<=t;q++){
        nr=0;
        scanf("%d%d\n",&n,&m);
        for(i=1;i<=n;i++){
            for(j=1;j<=m;j++){
                scanf("%c",&c);
                a[i][j]=c-'0';
            }
            scanf("\n");
        }
        for(i=0;i<=m+1;i++)
            a[0][i]=a[n+1][i]=0;
        for(i=0;i<=n+1;i++)
            a[i][0]=a[i][m+1]=0;
        for(i=1;i<=n;i++)
            for(j=1;j<=m;j++)
                if(a[i][j]==1)
                    nr+=verif(i,j);
        printf("%d\n",nr);
    }
    return 0;
}