/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author marX
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>

using namespace std;

class BDiceTower {
public:
    void solve(std::istream &in, std::ostream &out) {
        int t;
        in >> t;

        while (t--) {
            long long n;
            in >> n;

            bool ok = false;
            for (int i = 1; i <= 6 && !ok; ++i) {
                long long k = n - (21 - i);
                if (k < 0) continue;
                if (k % (21 - 7) == 0) ok = true;
            }

            out << (ok ? "YES" : "NO") << endl;
        }
    }
};


int main() {
    BDiceTower solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}