n, m = map(int, input().split())
A = list(map(int, input().split()))
B = list(map(int, input().split()))
A = list(map(lambda x: x % 2, A))
B = list(map(lambda x: x % 2, B))
s = A.count(0)
t = A.count(1)
s2 = B.count(0)
t2 = B.count(1)
print(min(s, t2) + min(t, s2))