#include<bits/stdc++.h>
using namespace std;
char a[500010];
int b[500010];
int c[500010];
int counti,n,i,j,brag,bebop,beblop;
stack<int> wow;
int main()
{
    cin>>n;
    for(i=1;i<=n;i++)
    {
        scanf("%s",&a);
        j=0;
        while(a[j]!='\0')
        {
            if(wow.empty())
            {
                if(a[j]=='(')
                {
                    wow.push(1);
                }
                else
                {
                    wow.push(-1);
                }
            }
            else
            {
                if(wow.top()==1)
                {
                if(a[j]=='(')
                {
                    wow.push(1);
                }
                else
                {
                    wow.pop();
                }
                }
                else
                {
                if(a[j]=='(')
                {
                    wow.push(1);
                }
                else
                {
                    wow.push(-1);
                }
                }
            }
            j++;
        }
        //cout<<"I'm a bug";
        j--;
        beblop=0;
        brag=0;
        if(!wow.empty()){
        bebop=wow.top();
        while(!wow.empty())
        {
            if(bebop!=wow.top())
            {
                beblop=-1;
                wow.pop();
                break;
            }
            else
            {
                wow.pop();
            }
        }
        j=0;
        if(beblop==0)
        {
        while(a[j]!='\0')
        {
            if(wow.empty())
            {
                if(a[j]=='(')
                {
                    wow.push(1);
                }
                else
                {
                    wow.push(-1);
                }
            }
            else
            {
                if(wow.top()==1)
                {
                if(a[j]=='(')
                {
                    wow.push(1);
                }
                else
                {
                    wow.pop();
                }
                }
                else
                {
                if(a[j]=='(')
                {
                    wow.push(1);
                }
                else
                {
                    wow.push(-1);
                }
                }
            }
            j++;
        }
        brag=wow.top()*wow.size();
        }}
        if(beblop==0)
        {
            //cout<<brag<<" "<<beblop<<" "<<wow.size()<<" " ;
            //cout<<"__________________";
            if(brag>0)
            {
                if(c[brag]>0)
                {
                    c[brag]--;
                    counti++;
                }
                else
                {
                    b[brag]++;
                }
            }
            else if (brag<0)
            {
                if(b[-brag]>0)
                {
                    b[-brag]--;
                    counti++;
                }
                else
                {
                    c[-brag]++;
                }
            }
            else
            {
                if(b[0]>0)
                {
                    b[0]--;
                    counti++;
                }
                else
                {
                    b[0]++;
                }
            }
        }
        while(!wow.empty())
        {
            wow.pop();
        }
        //cout<<c[2]<<"\n";
    }
    cout<<counti;
}