#include<cmath>
#include<math.h>
#include<ctype.h>
#include<algorithm>
#include<bitset>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<complex>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<typeinfo>
#include<utility>
#include<valarray>
#include<vector>
#include<string.h>
#include<stdlib.h>
#include<stdio.h>
#include<Windows.h>
using namespace std;
int n,m,i,o,p,j,k,l,s,a[60],v;
int main()
{
    cin>>n>>v;
    for(i=1;i<=n;i++){
                      cin>>m;
                      l=0;
                      for(j=1;j<=m;j++){
                                        cin>>k;
                                        if(k<v)l++;
                      }
                      if(l!=0){
                               s++;
                               a[s]=i;
                      }
    }
    cout<<s<<endl;
    for(i=1;i<s;i++){
                      cout<<a[i]<<' ';
    }
    if(s!=0)cout<<a[s]<<endl;                                   
                               
                                        
    //system("pause");
    return 0;
}