#include <bits/stdc++.h>
#ifdef LOC
#define deb _deb
#else
#define deb(...)
#endif
#define x  first
#define y second
#define mp make_pair
#define pb push_back
#define sz(x)int((x).size())
#define each(a,x)for(auto&a:(x))
#define all(x)(x).begin(),(x).end()
#define rep(i,b,e)for(int i=(b);i<(e);i++)
#define tem template<class t,class u,class...w>
#define DBP(...)void print(...){DD(#__VA_ARGS__,__VA_ARGS__);}
#define pri(y)tem auto operator<<(t&o,u a)->decltype(y(a),o){return o<<
#define _deb(...)(DD("#, "#__VA_ARGS__,__LINE__,__VA_ARGS__),cerr<<endl)
using ll=long long;pri(a.print)"{",a.print(),o<<"}";}using namespace std;void DD(...){}using Pii=pair<int
,int>;tem void DD(t s,u a,w...k){while(*s&&*s!=',')cerr<<*s++;cerr<<": "<<a<<*s++;DD(s,k...);}pri(all)"["
,[&](){for(auto i : a)o<<i<<", ";}(),o<<"]";}using  Vi=vector<int>;pri(get<1>) "("<<a.x<<", "<<a.y<<")";}
//-----------------------------------------------------------------------------------------------------//

const string STR[] = {
	"!x&x",
	"!(x|y|z)",
	"!x&!y&z",
	"!x&!y",
	"!x&!z&y",
	"!x&!z",
	"!(!y&!z|x|y&z)",
	"!(x|y&z)",
	"!x&y&z",
	"!(!y&z|!z&y|x)",
	"!x&z",
	"!(!z&y|x)",
	"!x&y",
	"!(!y&z|x)",
	"!x&(y|z)",
	"!x",
	"!y&!z&x",
	"!y&!z",
	"!(!x&!z|x&z|y)",
	"!(x&z|y)",
	"!(!x&!y|x&y|z)",
	"!(x&y|z)",
	"!(!x&!y|x&y|z)|!x&!y&z",
	"!((x|y)&z|x&y)",
	"!x&y&z|!y&!z&x",
	"!x&y&z|!y&!z",
	"!x&z|!y&!z&x",
	"!x&z|!y&!z",
	"!x&y|!y&!z&x",
	"!x&y|!y&!z",
	"!x&(y|z)|!y&!z&x",
	"!x|!y&!z",
	"!y&x&z",
	"!(!x&z|!z&x|y)",
	"!y&z",
	"!(!z&x|y)",
	"!x&!z&y|!y&x&z",
	"!x&!z|!y&x&z",
	"!x&!z&y|!y&z",
	"!x&!z|!y&z",
	"!x&y&z|!y&x&z",
	"!(!x&z|!z&x|y)|!x&y&z",
	"!(x&y)&z",
	"!(!z&x|y)|!x&z",
	"!x&y|!y&x&z",
	"!(!y&z|x)|!y&x&z",
	"!x&y|!y&z",
	"!x|!y&z",
	"!y&x",
	"!(!x&z|y)",
	"!y&(x|z)",
	"!y",
	"!x&!z&y|!y&x",
	"!x&!z|!y&x",
	"!x&!z&y|!y&(x|z)",
	"!x&!z|!y",
	"!x&y&z|!y&x",
	"!(!x&z|y)|!x&y&z",
	"!x&z|!y&x",
	"!x&z|!y",
	"!x&y|!y&x",
	"!(!x&!y&z|x&y)",
	"!x&(y|z)|!y&x",
	"!x|!y",
	"!z&x&y",
	"!(!x&y|!y&x|z)",
	"!x&!y&z|!z&x&y",
	"!x&!y|!z&x&y",
	"!z&y",
	"!(!y&x|z)",
	"!x&!y&z|!z&y",
	"!x&!y|!z&y",
	"!x&y&z|!z&x&y",
	"!(!x&y|!y&x|z)|!x&y&z",
	"!x&z|!z&x&y",
	"!(!z&y|x)|!z&x&y",
	"!(x&z)&y",
	"!(!y&x|z)|!x&y",
	"!x&z|!z&y",
	"!x|!z&y",
	"!z&x",
	"!(!x&y|z)",
	"!x&!y&z|!z&x",
	"!x&!y|!z&x",
	"!z&(x|y)",
	"!z",
	"!x&!y&z|!z&(x|y)",
	"!x&!y|!z",
	"!x&y&z|!z&x",
	"!(!x&y|z)|!x&y&z",
	"!x&z|!z&x",
	"!(!x&!z&y|x&z)",
	"!x&y|!z&x",
	"!x&y|!z",
	"!x&(y|z)|!z&x",
	"!x|!z",
	"!y&x&z|!z&x&y",
	"!(!x&y|!y&x|z)|!y&x&z",
	"!y&z|!z&x&y",
	"!(!z&x|y)|!z&x&y",
	"!y&x&z|!z&y",
	"!(!y&x|z)|!y&x&z",
	"!y&z|!z&y",
	"!(!y&!z&x|y&z)",
	"!x&y&z|!y&x&z|!z&x&y",
	"!(!x&y|!y&x|z)|!x&y&z|!y&x&z",
	"!(x&y)&z|!z&x&y",
	"!(!z&x|y)|!x&z|!z&x&y",
	"!(x&z)&y|!y&x&z",
	"!(!y&x|z)|!x&y|!y&x&z",
	"!(x&y)&z|!z&y",
	"!x|!y&z|!z&y",
	"!(y&z)&x",
	"!(!x&y|z)|!y&x",
	"!y&z|!z&x",
	"!y|!z&x",
	"!y&x|!z&y",
	"!y&x|!z",
	"!y&(x|z)|!z&y",
	"!y|!z",
	"!(y&z)&x|!x&y&z",
	"!(!x&y|z)|!x&y&z|!y&x",
	"!(x&y)&z|!z&x",
	"!x&z|!y|!z&x",
	"!(x&z)&y|!y&x",
	"!x&y|!y&x|!z",
	"!x&y|!y&z|!z&x",
	"!(x&y&z)",
	"x&y&z",
	"!(x|y|z)|x&y&z",
	"!x&!y&z|x&y&z",
	"!x&!y|x&y&z",
	"!x&!z&y|x&y&z",
	"!x&!z|x&y&z",
	"!(!y&!z|x|y&z)|x&y&z",
	"!(x|y&z)|x&y&z",
	"y&z",
	"!(x|y|z)|y&z",
	"!x&z|y&z",
	"!x&!y|y&z",
	"!x&y|y&z",
	"!x&!z|y&z",
	"!x&(y|z)|y&z",
	"!x|y&z",
	"!y&!z&x|x&y&z",
	"!y&!z|x&y&z",
	"!(!x&!z|x&z|y)|x&y&z",
	"!(x&z|y)|x&y&z",
	"!(!x&!y|x&y|z)|x&y&z",
	"!(x&y|z)|x&y&z",
	"!(!x&!y|x&y|z)|!x&!y&z|x&y&z",
	"!((x|y)&z|x&y)|x&y&z",
	"!y&!z&x|y&z",
	"!y&!z|y&z",
	"!x&z|!y&!z&x|y&z",
	"!(x&z|y)|y&z",
	"!x&y|!y&!z&x|y&z",
	"!(x&y|z)|y&z",
	"!x&(y|z)|!y&!z&x|y&z",
	"!x|!y&!z|y&z",
	"x&z",
	"!(x|y|z)|x&z",
	"!y&z|x&z",
	"!x&!y|x&z",
	"!x&!z&y|x&z",
	"!x&!z|x&z",
	"!x&!z&y|!y&z|x&z",
	"!(x|y&z)|x&z",
	"(x|y)&z",
	"!(x|y|z)|(x|y)&z",
	"z",
	"!x&!y|z",
	"!x&y|x&z",
	"!(!y&z|x)|x&z",
	"!x&y|z",
	"!x|z",
	"!y&x|x&z",
	"!y&!z|x&z",
	"!y&(x|z)|x&z",
	"!y|x&z",
	"!x&!z&y|!y&x|x&z",
	"!(x&y|z)|x&z",
	"!x&!z&y|!y&(x|z)|x&z",
	"!x&!z|!y|x&z",
	"!y&x|y&z",
	"!(!x&z|y)|y&z",
	"!y&x|z",
	"!y|z",
	"!x&y|!y&x|x&z",
	"!x&!z|!y&x|y&z",
	"!x&y|!y&x|z",
	"!x|!y|z",
	"x&y",
	"!(x|y|z)|x&y",
	"!x&!y&z|x&y",
	"!x&!y|x&y",
	"!z&y|x&y",
	"!x&!z|x&y",
	"!x&!y&z|!z&y|x&y",
	"!(x|y&z)|x&y",
	"(x|z)&y",
	"!(x|y|z)|(x|z)&y",
	"!x&z|x&y",
	"!(!z&y|x)|x&y",
	"y",
	"!x&!z|y",
	"!x&z|y",
	"!x|y",
	"!z&x|x&y",
	"!y&!z|x&y",
	"!x&!y&z|!z&x|x&y",
	"!(x&z|y)|x&y",
	"!z&(x|y)|x&y",
	"!z|x&y",
	"!x&!y&z|!z&(x|y)|x&y",
	"!x&!y|!z|x&y",
	"!z&x|y&z",
	"!(!x&y|z)|y&z",
	"!x&z|!z&x|x&y",
	"!x&!y|!z&x|y&z",
	"!z&x|y",
	"!z|y",
	"!x&z|!z&x|y",
	"!x|!z|y",
	"(y|z)&x",
	"!(x|y|z)|(y|z)&x",
	"!y&z|x&y",
	"!(!z&x|y)|x&y",
	"!z&y|x&z",
	"!(!y&x|z)|x&z",
	"!y&z|!z&y|x&y",
	"!x&!y|!z&y|x&z",
	"(x|y)&z|x&y",
	"!(x|y|z)|(x|y)&z|x&y",
	"x&y|z",
	"!x&!y|x&y|z",
	"x&z|y",
	"!x&!z|x&z|y",
	"y|z",
	"!x|y|z",
	"x",
	"!y&!z|x",
	"!y&z|x",
	"!y|x",
	"!z&y|x",
	"!z|x",
	"!y&z|!z&y|x",
	"!y|!z|x",
	"x|y&z",
	"!y&!z|x|y&z",
	"x|z",
	"!y|x|z",
	"x|y",
	"!z|x|y",
	"x|y|z",
	"!x|x",
};

void run() {
	string bin; cin >> bin;
	int m = 0;
	rep(i, 0, 8) if (bin[i] == '1') m |= (1<<i);
	cout << STR[m] << '\n';
}

int main() {
	cin.sync_with_stdio(0); cin.tie(0);
	cout << fixed << setprecision(10);

	int n; cin >> n;
	while (n--) run();
	return 0;
}