#include <iostream>
#include <vector>
#include <algorithm>
#include <string>
#include <ctype.h>
#include <cstring>
#include <stdio.h>
using namespace std;
typedef long long ll;
typedef long double ld;
typedef std::vector<int> vi;
#define forn(i, a, b) for(int i = a; i < b; i++)
#define pb push_back
#define SZ 233333
const int MOD=998244353; //or any prime
ll qp(ll a,ll b)
{
    ll x=1; a%=MOD;
    while(b)
    {
        if(b&1) x=x*a%MOD;
        a=a*a%MOD; b>>=1;
    }
    return x;
}
namespace linear_seq {
    inline vector<int> BM(vector<int> x)
    {
        vector<int> ls,cur;
        int lf,ld;
        for(int i=0;i<int(x.size());++i)
        {
            ll t=0;
            for(int j=0;j<int(cur.size());++j)
                t=(t+x[i-j-1]*(ll)cur[j])%MOD;
            if((t-x[i])%MOD==0) continue; //good so far
            if(!cur.size())
            {
                cur.resize(i+1);
                lf=i; ld=(t-x[i])%MOD;
                continue;
            }
            ll k=-(x[i]-t)*qp(ld,MOD-2)%MOD/*1/ld*/;
            vector<int> c(i-lf-1); //add zeroes in front
            c.pb(k);
            for(int j=0;j<int(ls.size());++j)
                c.pb(-ls[j]*k%MOD);
            if(c.size()<cur.size()) c.resize(cur.size());
            for(int j=0;j<int(cur.size());++j)
                c[j]=(c[j]+cur[j])%MOD;
            if(i-lf+(int)ls.size()>=(int)cur.size())
                ls=cur,lf=i,ld=(t-x[i])%MOD;
            cur=c;
        }
        for(int i=0;i<int(cur.size());++i)
            cur[i]=(cur[i]%MOD+MOD)%MOD;
        return cur;
    }
    int m;
    ll a[SZ],h[SZ],t_[SZ],s[SZ],t[SZ];
    inline void mull(ll*p,ll*q)
    {
        for(int i=0;i<m+m;++i) t_[i]=0;
        for(int i=0;i<m;++i) if(p[i])
            for(int j=0;j<m;++j)
                t_[i+j]=(t_[i+j]+p[i]*q[j])%MOD;
        for(int i=m+m-1;i>=m;--i) if(t_[i])
            for(int j=m-1;~j;--j)
                t_[i-j-1]=(t_[i-j-1]+t_[i]*h[j])%MOD;
        for(int i=0;i<m;++i) p[i]=t_[i];
    }
    inline ll calc(ll K)
    {
        for(int i=m;~i;--i)
            s[i]=t[i]=0;
        s[0]=1; if(m!=1) t[1]=1; else t[0]=h[0];
        while(K)
        {
            if(K&1) mull(s,t);
            mull(t,t); K>>=1;
        }
        ll su=0;
        for(int i=0;i<m;++i) su=(su+s[i]*a[i])%MOD;
        return (su%MOD+MOD)%MOD;
    }
    inline int work(vector<int> x,ll n)
    {
        if(n<int(x.size())) return x[n];
        vector<int> v=BM(x); m=v.size(); if(!m) return 0;
        for(int i=0;i<m;++i) h[i]=v[i],a[i]=x[i];
        return calc(n);
    }
}
using linear_seq::work;
vi d[23][23];
vi add[23][23];

int main()
{
#ifdef LOCAL
    freopen("input.txt", "rt", stdin);
    freopen("output.txt", "wt", stdout);
#endif
    vector<string> st;
    st.pb("bddddd");
    st.pb("bcccccccccc");
    st.pb("bcdcdcdcdcd");
    st.pb("bcccccccccccccc");
    st.pb("bccdccdccdccdcc");
    st.pb("bcccccccccccccccccc");
    st.pb("bcccdcccdcccdcccdcc");
    st.pb("bcccccccccccccccccccccc");
    st.pb("bccccdccccdccccdccccdcc");
    st.pb("bcccccccccccccccccccccccccc");
    st.pb("bcccccdcccccdcccccdcccccdcc");
    st.pb("bcccccccccccccccccccccccccccccc");
    st.pb("bccccccdccccccdccccccdccccccdcc");
    st.pb("bcccccccccccccccccccccccccccccccccc");
    st.pb("bcccccccdcccccccdcccccccdcccccccdcc");
    st.pb("bcccccccccccccccccccccccccccccccccccccc");
    st.pb("bccccccccdccccccccdccccccccdccccccccdcc");
    st.pb("bcccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bcccccccccdcccccccccdcccccccccdcccccccccdcc");
    st.pb("bcccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bccccccccccdccccccccccdccccccccccdccccccccccdcc");
    st.pb("bbebebebebebeb");
    st.pb("bbfbfbfbfbfbfb");
    st.pb("bbddbddbddbddbddbddbdd");
    st.pb("bbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbdbebdbebdbebdbebdbebdbebdbeb");
    st.pb("bbdbfbdbfbdbfbdbfbdbfbdbfbdbfb");
    st.pb("bbdbddbdbddbdbddbdbddbdbddbdbddbdbddbd");
    st.pb("bbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbdbdbebdbdbebdbdbebdbdbebdbdbebdbdbebdbdbebdb");
    st.pb("bbdbdbfbdbdbfbdbdbfbdbdbfbdbdbfbdbdbfbdbdbfbdb");
    st.pb("bbdbdbddbdbdbddbdbdbddbdbdbddbdbdbddbdbdbddbdbdbddbdbd");
    st.pb("bbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbdbdbdbebdbdbdbebdbdbdbebdbdbdbebdbdbdbebdbdbdbebdbdbdbebdbdb");
    st.pb("bbdbdbdbfbdbdbdbfbdbdbdbfbdbdbdbfbdbdbdbfbdbdbdbfbdbdbdbfbdbdb");
    st.pb("bbdbdbdbddbdbdbdbddbdbdbdbddbdbdbdbddbdbdbdbddbdbdbdbddbdbdbdbddbdbdbd");
    st.pb("bbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbdbdbdbdbebdbdbdbdbebdbdbdbdbebdbdbdbdbebdbdbdbdbebdbdbdbdbebdbdbdbdbebdbdbdb");
    st.pb("bbdbdbdbdbfbdbdbdbdbfbdbdbdbdbfbdbdbdbdbfbdbdbdbdbfbdbdbdbdbfbdbdbdbdbfbdbdbdb");
    st.pb("bbdbdbdbdbddbdbdbdbdbddbdbdbdbdbddbdbdbdbdbddbdbdbdbdbddbdbdbdbdbddbdbdbdbdbddbdbdbdbd");
    st.pb("bbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbfbbfbbfbbfbbfbbfbbfbbfb");
    st.pb("bbbeccccccccccccccccccccccccccccccc");
    st.pb("bbbhbbhbbhbbhbbhbbhbbhbbhbbh");
    st.pb("bbbeccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbebebbebebbebebbebebbebebbebebbebebbebebbebebbe");
    st.pb("bbbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebb");
    st.pb("bbbebbfbbebbfbbebbfbbebbfbbebbfbbebbfbbebbfbbebbfbbebbfbbebb");
    st.pb("bbbebbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbebbhbbebbhbbebbhbbebbhbbebbhbbebbhbbebbhbbebbhbbebbhbbebbhbb");
    st.pb("bbbebbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbebbebebbebbebebbebbebebbebbebebbebbebebbebbebebbebbebebbebbebebbebbebebbebbebebbeb");
    st.pb("bbbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebb");
    st.pb("bbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebbebbfbbebb");
    st.pb("bbbebbebbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebbhbbebbebb");
    st.pb("bbbebbebbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbebebbebbebbeb");
    st.pb("bbbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebb");
    st.pb("bbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebbfbbebbebbebb");
    st.pb("bbbbgbbbgbbbgbbbgbbbgbbbgbbbgbbbgbbbgbbb");
    st.pb("bbbbhbbbhbbbhbbbhbbbhbbbhbbbhbbbhbbbhbbbhbbb");
    st.pb("bbbbfdbccddbccddbccddbccddbccddbccddbccddbccddbccddbccdd");
    st.pb("bbbbjbbbjbbbjbbbjbbbjbbbjbbbjbbbjbbbjbbbjbbbjbbb");
    st.pb("bbbbfcdbccdcdbccdcdbccdcdbccdcdbccdcdbccdcdbccdcdbccdcdbccdcdbccdcdbccdc");
    st.pb("bbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfbbbfbfb");
    st.pb("bbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbbfbbfbbb");
    st.pb("bbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfb");
    st.pb("bbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbbgbbbfbbb");
    st.pb("bbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbbhbbbfbbb");
    st.pb("bbbbfbbbfdbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddbccdbccddb");
    st.pb("bbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbbfbbbjbbb");
    st.pb("bbbbfbbbfcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccdbccdcdbccd");
    st.pb("bbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbbfbfbbbfbbb");
    st.pb("bbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbbfbbfbbbfbbb");
    st.pb("bbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfb");
    st.pb("bbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbbgbbbfbbbfbbb");
    st.pb("bbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbbhbbbfbbbfbbb");
    st.pb("bbbbbhbbbbhbbbbhbbbbhbbbbhbbbbhbbbbhbbbbhbbbbhbbbbhbbbbhbbbb");
    st.pb("bbbbbgccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbgdbcbdddbcbdddbcbdddbcbdddbcbdddbcbdddbcbdddbcbdddbcbdddbcbdddbcbdddbcbddd");
    st.pb("bbbbbgccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbblbbbb");
    st.pb("bbbbbgccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbgbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddbddbcbddb");
    st.pb("bbbbbgbbeccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbbgbbbgbbbb");
    st.pb("bbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbbgbbbb");
    st.pb("bbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbbhbbbbgbbbb");
    st.pb("bbbbbgbbbbgccbbeccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbgbbbbgdbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddbcbddbcbdddb");
    st.pb("bbbbbgbbbbgcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbbgbbbblbbbb");
    st.pb("bbbbbgbbbbgcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbgbbbbgbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbddbddbcbddbcbd");
    st.pb("bbbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbbibbbbb");
    st.pb("bbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbbjbbbbb");
    st.pb("bbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbkbbbbbk");
    st.pb("bbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbhcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdbccccdcdb");
    st.pb("bbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbbnbbbbb");
    st.pb("bbbbbbhccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdccdbccccdcc");
    st.pb("bbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbhbbhbbbbbh");
    st.pb("bbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbbhbbbbbhbbb");
    st.pb("bbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbbbbhbbbbhbbb");
    st.pb("bbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbbhbbbbb");
    st.pb("bbbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbbbbibbbbbhbbb");
    st.pb("bbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbbjbbbbbhbbbbb");
    st.pb("bbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbkbbbbbhbbbbbk");
    st.pb("bbbbbbhbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbbjbbbbbb");
    st.pb("bbbbbbbiccbbbbgccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbidbcbbbfddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccdddbcbccddd");
    st.pb("bbbbbbbiccccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbibebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebbdbdbebebb");
    st.pb("bbbbbbbiccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbbbbbbpbb");
    st.pb("bbbbbbbiccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbibdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdbebbdbdbebdb");
    st.pb("bbbbbbbibbeccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbibbbfdbcbbbfdbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccddbccddbcbccd");
    st.pb("bbbbbbbibbbbgccbbbbgccbbeccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibbbbbbibbbbbibb");
    st.pb("bbbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbbibbbbbb");
    st.pb("bbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibbbbbbjbbbbbbibb");
    st.pb("bbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbbkbbbbbbb");
    st.pb("bbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbbbblbbbbb");
    st.pb("bbbbbbbbjdbcbbbbgddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbddddbcbcbdddd");
    st.pb("bbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbbnbbbbbbb");
    st.pb("bbbbbbbbjbebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbdbbebebebbd");
    st.pb("bbbbbbbbjbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfbfbbbdbdbfb");
    st.pb("bbbbbbbbjccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbccccccdccdbcc");
    st.pb("bbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbbrbbbbbbb");
    st.pb("bbbbbbbbjcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbccccccdcccdbc");
    st.pb("bbbbbbbbjbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdbfbdbfbbbdbdb");
    st.pb("bbbbbbbbjbbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbebebbdbbebebbeb");
    st.pb("bbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbbbbjbbbjbbbbb");
    st.pb("bbbbbbbbjbbbbgdbcbbbbgdbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdddbcbdddbcbcbdd");
    st.pb("bbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbbjbbbbbbbjbbbbb");
    st.pb("bbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbblbbbbbbbb");
    st.pb("bbbbbbbbbkccbbbbbbiccccbbbbgccccccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbnbbbbbbbbn");
    st.pb("bbbbbbbbbkccccbbbbgcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbkcdbccbbbfcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccbccdcdcdbccb");
    st.pb("bbbbbbbbbkbbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebb");
    st.pb("bbbbbbbbbkbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdbdbddbddbcbdb");
    st.pb("bbbbbbbbbkccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbbtbbbbbbbb");
    st.pb("bbbbbbbbbkccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbkbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcbdbdbddbdbddbcb");
    st.pb("bbbbbbbbbkbbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebb");
    st.pb("bbbbbbbbbkbbbfcdbccbbbfcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccdcdbccbccdcdbccd");
    st.pb("bbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbbbmbbbbbbbb");
    st.pb("bbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbbbbbbnbbbbb");
    st.pb("bbbbbbbbbbldbcbbbbbbiddbcbcbbbfdddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccddddbcbcbccdddd");
    st.pb("bbbbbbbbbblbdbdbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbbqbbbbbbbbb");
    st.pb("bbbbbbbbbblbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfbfbbbdbbbfbfb");
    st.pb("bbbbbbbbbblbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbebbfbbfbbbebbeb");
    st.pb("bbbbbbbbbblbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbbbblcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccccdcccdbccccccc");
    st.pb("bbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbbvbbbbbbbbb");
    st.pb("bbbbbbbbbblccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccccccdccccdbccccc");
    st.pb("bbbbbbbbbblbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbbbbnbbbbbbbb");
    st.pb("bbbbbbbbbbbmccbbbbbbbbkccccbbbbbbiccccccbbbbgccccccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbmdbcbbbbbbbjddbcbcbbbbgdddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbdddddbcbcbcbddddd");
    st.pb("bbbbbbbbbbbmccccbbbbbbiccccccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbmcdbccbbbbbhcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbccccdcdcdbccbcc");
    st.pb("bbbbbbbbbbbmccccccbbbbgcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbmbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbbfbbfbbbebbbfbb");
    st.pb("bbbbbbbbbbbmbbeccbbebbebbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbmbdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdbebdbebbdbdbdbdb");
    st.pb("bbbbbbbbbbbmccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbbxbbbbbbbbbb");
    st.pb("bbbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbbbbbobbbbbbbb");
    st.pb("bbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbbbbbbbbpbbbbb");
    st.pb("bbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbqbbbbbbbbbbbq");
    st.pb("bbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbbrbbbbbbbbbbb");
    st.pb("bbbbbbbbbbbbnbebbdbbbbbbibebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdbdbebebebbdbbdb");
    st.pb("bbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbbbbbbbbbbtbbb");
    st.pb("bbbbbbbbbbbbnbddbcbdbbbbgbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbddbddbcbdbcbddbd");
    st.pb("bbbbbbbbbbbbnbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfbbbfb");
    st.pb("bbbbbbbbbbbbnbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbbhbbbbbebbebbhbb");
    st.pb("bbbbbbbbbbbbnbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdbdbdbfbdbfbbbdbdb");
    st.pb("bbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbbbbbbpbbbbbbbb");
    st.pb("bbbbbbbbbbbbboccbbbbbbbbbbmccccbbbbbbbbkccccccbbbbbbiccccccccbbbbgccccccccccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbodbcbbbbbbbbblddbcbcbbbbbbidddbcbcbcbbbfddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccdddddbcbcbcbccddddd");
    st.pb("bbbbbbbbbbbbboccccbbbbbbbbkccccccccbbbbgccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbobebbdbbbbbbbjbebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbbebebebebbdbbdbb");
    st.pb("bbbbbbbbbbbbboccccccbbbbbbicccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbboccdbcccbbbbbhccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccdccdbcccbccccdccd");
    st.pb("bbbbbbbbbbbbbobbeccbbebbbbgbbeccccccccccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbobbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbbgbbbbfbbbfbbbgbbb");
    st.pb("bbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbbbbbbbqbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbbbbbbbbbbrbbbbb");
    st.pb("bbbbbbbbbbbbbbpdbcbbbbbbbbbbmddbcbcbbbbbbbjdddbcbcbcbbbbgddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbddddddbcbcbcbcbdddddd");
    st.pb("bbbbbbbbbbbbbbpbdbdbbbbbbbbblbdbdbdbdbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbbbbbbbbpcdbccbbbbbbbbkcdcdbccbccbbbfcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbccdcdcdcdbccbccbcc");
    st.pb("bbbbbbbbbbbbbbpbfbbbdbbbbbbbjbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdbbbdbdbfbfbfbbbdb");
    st.pb("bbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbbwbbbbbbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbpbdbdbdbdbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbbbbbbbbrbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbqccbbbbbbbbbbbboccccbbbbbbbbbbmccccccbbbbbbbbkccccccccbbbbbbiccccccccccbbbbgccccccccccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbtbbbbbbbbbbbbbbt");
    st.pb("bbbbbbbbbbbbbbbqccccbbbbbbbbbbmccccccccbbbbbbiccccccccccccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbbvbbbbbbbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbqbbebbebbbbbbbbkbbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebbebb");
    st.pb("bbbbbbbbbbbbbbbqccdbcccbbbbbbbjccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdccdbcccbccccccdccdcc");
    st.pb("bbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbbbbbbbbbsbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbtbbbbb");
    st.pb("bbbbbbbbbbbbbbbbrdbcbbbbbbbbbbbboddbcbcbbbbbbbbbldddbcbcbcbbbbbbiddddbcbcbcbcbbbfdddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccddddddbcbcbcbcbccdddddd");
    st.pb("bbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbbrcdbccbbbbbbbbbbmcdcdbccbccbbbbbhcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbccccdcdcdcdbccbccbcccc");
    st.pb("bbbbbbbbbbbbbbbbrbfbbbdbbbbbbbbblbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbbdbbbfbfbfbfbbbdbbb");
    st.pb("bbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbbbbbbbbbbtbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbbbsccbbbbbbbbbbbbbbqccccbbbbbbbbbbbboccccccbbbbbbbbbbmccccccccbbbbbbbbkccccccccccbbbbbbiccccccccccccbbbbgccccccccccccccbbecccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbbbbbsdbcbbbbbbbbbbbbbpddbcbcbbbbbbbbbbmdddbcbcbcbbbbbbbjddddbcbcbcbcbbbbgdddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbdddddddbcbcbcbcbcbddddddd");
    st.pb("bbbbbbbbbbbbbbbbbsccccbbbbbbbbbbbboccccccccbbbbbbbbkccccccccccccbbbbgcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbbbbbsbebbdbbbbbbbbbbbnbebebbdbbdbbbbbbibebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdbebebebebbdbbdbbdbdb");
    st.pb("bbbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbbbbbbbbbbbubbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbvbbbbb");
    st.pb("bbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbw");
    st.pb("bbbbbbbbbbbbbbbbbbtbdbdbbbbbbbbbbbbbpbdbdbdbdbbbbbbbbblbdbdbdbdbdbdbbbbbhbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdbdb");
    st.pb("bbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbbbbbbbbbbbbvbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbbbbbuccbbbbbbbbbbbbbbbbsccccbbbbbbbbbbbbbbqccccccbbbbbbbbbbbboccccccccbbbbbbbbbbmccccccccccbbbbbbbbkccccccccccccbbbbbbiccccccccccccccbbbbgccccccccccccccccbbeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc");
    st.pb("bbbbbbbbbbbbbbbbbbbudbcbbbbbbbbbbbbbbbrddbcbcbbbbbbbbbbbbodddbcbcbcbbbbbbbbblddddbcbcbcbcbbbbbbidddddbcbcbcbcbcbbbfddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccdddddddbcbcbcbcbcbccddddddd");
    st.pb("bbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbwbbbbbbbb");
    st.pb("bbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbxbbbbb");
    st.pb("bbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbbbbbbbbbbbbbbxbbbbbbbb");
    int pt = 0;
    forn(x,1,23) forn(y,x,23) {
        if(x==y) continue;
        for(auto c : st[pt]) add[x][y].pb(c-'a');
        pt++;
        forn(i,1,add[x][y].size()) add[x][y][i] += add[x][y][i-1];
        d[x][y] = vi(x*y*4+10,0);
        for(auto it : add[x][y]) if(it<d[x][y].size()) d[x][y][it]++;
        forn(i,1,d[x][y].size()) d[x][y][i] += d[x][y][i-1];
    }
    int n,x,y;
    cin>>n>>x>>y;
    if(x>y) swap(x,y);
    if(x!=y) cout<<work(d[x][y], n);
    else cout<<(n/(2*x)*x + min(n%(2*x),x));
}