#include "bits/stdc++.h"
using namespace std;
#define N 2002
char a[N][N],ch='z',ans[N];
int dp[N][N],x[2][N*2],y[2][N*2],n,k,sum,max1,jud[N][N],c,sum1,px,py;
int main()
{
	cin>>n>>k;
	int i,j;
	for(i=0;i<n;i++)
	cin>>a[i];
	for(i=0;i<=n;i++)
	dp[0][i]=dp[i][0]=k;
	for(i=0;i<n;i++)
	{
		for(j=0;j<n;j++)
		{
			if(i+j>dp[i+1][j]&&i+j>dp[i][j+1])continue;
			if(a[i][j]=='a')dp[i+1][j+1]=max(dp[i+1][j]+1,dp[i][j+1]+1);
			else dp[i+1][j+1]=max(dp[i+1][j],dp[i][j+1]);
			if(i+j>=dp[i+1][j+1])
			{
				if(i+j==dp[i+1][j+1])
				{
				//cout<<sum<<"sum\n";
					if(max1<i+j)
					{
						max1=i+j;
						ch='z';
						sum=0;
					}
					if(max1==i+j&&a[i][j]<=ch)
					{
						if(a[i][j]<ch)
						{
							ch=a[i][j];
							sum=0;
						}
						x[0][sum]=i;
						y[0][sum]=j;
						sum++;
					}
				}
				dp[i+1][j+1]=0;
			}
			else
			{
				if(max1<i+j+1)
				{
					max1=i+j+1;
					ch='z';
					sum=0;
				}
			}
		}
	}
	for(i=0;i<max1;i++)
	ans[i]='a'; 
	ans[i]=ch;
	for(j=max1;j<2*n-2;j++)
	{
		c^=1;
		ch='z';
		sum1=0;
		for(i=0;i<sum;i++)
		{
			px=x[c^1][i],py=y[c^1][i];
			if(px<n-1&&(!jud[px+1][py]))
			{
				//cout<<"yes1\n";
				if(a[px+1][py]<ch)
				{
					ch=a[px+1][py];
					sum1=0;
				}
				if(ch==a[px+1][py])
				{
					x[c][sum1]=px+1,y[c][sum1]=py;
					sum1++;
					jud[px+1][py]=1;
				}
			}
			if(py<n-1&&(!jud[px][py+1]))
			{
				//cout<<"yes2\n";
				if(a[px][py+1]<ch)
				{
					ch=a[px][py+1];
					sum1=0;
				}
				if(ch==a[px][py+1])
				{
					x[c][sum1]=px,y[c][sum1]=py+1;
					sum1++;
					jud[px][py+1]=1;
				}
			}
		}
		sum=sum1;
		ans[j+1]=ch;
	}
	ans[2*n-1]=0;
	printf("%s",ans);
}