#include<stdio.h>
int i,j,n,a,b,c,tmp;
 
int main(){
	scanf("%lld",&n);
	tmp=0;
	for(i=1;i<=n;i++){
		scanf("%d%d%d",&a,&b,&c);
		if(b==0&a>0){
			for(j=1;j<=a+1;j++){
				printf("0");
			}
			printf("\n");continue;
		}
		if(b==0&c>0){
			for(j=1;j<=c+1;j++){
				printf("1");
			}
			printf("\n");continue;
		}
		if(b!=0&a==0){
			for(j=1;j<=c+1;j++){
				printf("1");
			}
			for(j=1;j<=b;j++){
				printf("%d",(j+1)%2);
			}
			printf("\n");continue;
		}
		if(b!=0&c==0){
			for(j=1;j<=a+1;j++){
				printf("0");
			}
			for(j=1;j<=b;j++){
				printf("%d",j%2);
			}
			printf("\n");continue;
		}
		for(j=1;j<=b;j++){
			printf("%d",j%2);
			tmp=j%2;
		}
		if(tmp==1){
			for(j=1;j<=c;j++){
				printf("1");
			}
			for(j=1;j<=a+1;j++){
				printf("0");
			}
			printf("\n");continue;
		}
		if(tmp==0){
			for(j=1;j<=a;j++){
				printf("0");
			}
			for(j=1;j<=c+1;j++){
				printf("1");
			}
			printf("\n");continue;
		}
	}
}