#include <iostream>
#include <iterator>
#include <string>
#include <tuple>
#include <utility>
namespace cm{class logger{private:std::ostream*_1a;std::string _13="\x2c\x20";bool _c=true;int _9=0;std::string _14="\033[0;31m";std::string _17="\033[0;32m";std::string _d="\033[0;33m";std::string _1b="\033[0;34m";std::string _12="\033[0;35m";std::string _15="\033[0;36m";std::string _16="\033[1;31m";std::string _18="\033[1;32m";std::string _a="\033[1;33m";std::string _19="\033[1;34m";std::string _1c="\033[1;35m";std::string _2="\033[1;36m";std::string _e="\033[0m";std::string _3(std::string _1d){if(_1d=="red")return _14;if(_1d=="green")return _17;if(_1d=="yellow")return _d;if(_1d=="blue")return _1b;if(_1d=="magenta")return _12;if(_1d=="cyan")return _15;if(_1d=="red bold")return _16;if(_1d=="green bold")return _18;if(_1d=="yellow bold")return _a;if(_1d=="blue bold")return _19;if(_1d=="magenta bold")return _1c;if(_1d=="cyan bold")return _2;if(_1d=="reset")return _e;return "";}public:logger(std::ostream&_1a):_1a(&_1a){}logger&set_ostream(std::ostream&_1a){this->_1a=&_1a;return*this;}logger&set_sep(const std::string&_13){this->_13=_13;return*this;}logger&assert_exit(){_c=true;return*this;}logger&assert_noexit(){_c=false;return*this;}logger&set_exit_code(int _4){_9=_4;return*this;}logger&endl(){*_1a<<std::endl;return*this;}logger&log(){return*this;}template<class Ta,class Tb,class...Tc>logger&log(const Ta&a,const Tb&b,Tc...c){return log(a).log(_13).log(b,c...);}template<class Ta,typename=decltype(std::cout<<std::declval<Ta>())>logger&log(const Ta&a){*_1a<<a;return*this;}template<class T,typename=decltype(std::declval<T>().begin()),typename=decltype(std::declval<T>().end()),typename=typename std::enable_if<!std::is_base_of<std::string,typename std::decay<T>::type>::value>::type,typename value_type=typename T::value_type>logger&log(const T&_f){log("{");for(auto it=_f.begin();it!=_f.end();++it){if(it!=_f.begin())log(_13);log(*it);}log("}");return*this;}template<class Ta,class Tb>logger&log(const std::pair<Ta,Tb>&x){return log("(").log(x.first,x.second).log(")");}
#if __cplusplus >= 201703L
template<class...T>logger&log(const std::tuple<T...>&x){log("(");std::apply([this](auto...x){this->log(x...);},x);return log(")");}
#else
template<class...T>logger&log(const std::tuple<T...>&){return log("<tuple>");}
#endif
template<class T>logger&hint(const T&x,std::string _10="cyan"){_10=_3(_10);return log(_10).log(x).log("\x3a\x20").log(_e);}template<class...T>logger&operator()(T..._11){return log(_11...).endl();}template<class...T>logger&_1(const std::string&_5,int _6,const std::string&_7,bool _11,const std::string&_b,T..._8){if(!_11){endl();hint(_5,"magenta").hint(_6,"magenta").log(_d).log("Assertion `").log(_a).log(_7).log(_d).log("` failed").log(_e).endl();if(_b!="")hint("detail","magenta").hint(_b)(_8...);if(_c)exit(_9);}return*this;}};namespace impl{logger see_logger(std::cout);}}
#define see(...)
#define asee(...)
#define cm_assert(...)
#include <cctype>
#include <cstdio>
namespace cm{template<class _1c,size_t _1b>class buffer_reader{protected:FILE*src;_1c*const buff;_1c*buff_end;_1c*buff_pos;void _12(){buff_end=buff+fread(buff,sizeof(_1c),_1b,src);buff_pos=buff;if(buff_end==buff){*buff_end='\0';}}public:buffer_reader(FILE*_14):src(_14),buff(new _1c[_1b]){_12();}buffer_reader(const buffer_reader&)=delete;buffer_reader(buffer_reader&&)=delete;buffer_reader&operator=(const buffer_reader&)=delete;buffer_reader&operator=(buffer_reader&&)=delete;_1c get()const{return*buff_pos;}_1c next(){_1c result=get();buff_pos++;if(buff_pos==buff_end)_12();return result;}~buffer_reader(){fclose(src);delete[]buff;}};using optimal_reader=buffer_reader<char,1<<16>;template<class _18>class scanner:protected _18{private:using _18::get;using _18::next;inline bool _15(char c){return c<=' ';}inline bool _17(char c){return c=='\n'||c=='\r';}int _16(){while(!isdigit(get())&&get()!='-')next();if(get()=='-')return next(),-1;return 1;}public:scanner()=delete;using _18::_18;char next_char(){while(_15(get()))next();return next();}char*next_token(char*s){while(_15(get()))next();while(!_15(get()))*s++=next();*s='\0';return s;}char*next_line(char*s){while(_15(get()))next();while(!_17(get()))*s++=next();*s='\0';return s;}int next_int(){int sign=_16();int result=0;while(isdigit(get()))result=result*10+(next()-'0');return sign*result;}long long next_long(){int sign=_16();long long result=0;while(isdigit(get()))result=result*10+(next()-'0');return sign*result;}template<class _19>_19 next_integer(){_19 sign=_16();_19 result(0);while(isdigit(get()))result=result*_19(10)+_19(next()-'0');return sign*result;}double next_double(){int sign=_16();double result=0;while(isdigit(get()))result=result*10+(next()-'0');if(get()=='.'){next();double cur_ep=0.1;while(isdigit(get()))result+=cur_ep*(next()-'0'),cur_ep*=0.1;}return sign*result;}};}
#include <utility>
#include <vector>
#define _1b inline __attribute__((always_inline))
namespace cm{template<class T>inline bool check_min(T&a,const T&b){return b<a?a=b,1:0;}template<class T>inline bool check_max(T&a,const T&b){return a<b?a=b,1:0;}struct once_t{bool _14=true;bool operator()(){return _14?(_14=false,true):false;}};}using cm::check_max;using cm::check_min;template<class A,class B>_1b std::pair<A,B>operator+(const std::pair<A,B>&lhs,const std::pair<A,B>&rhs){return std::make_pair(lhs.first+rhs.first,lhs.second+rhs.second);}template<class A,class B>_1b std::pair<A,B>operator-(const std::pair<A,B>&lhs,const std::pair<A,B>&rhs){return std::make_pair(lhs.first-rhs.first,lhs.second-rhs.second);}template<class A,class B>_1b std::pair<A,B>&operator+=(std::pair<A,B>&lhs,const std::pair<A,B>&rhs){lhs.first+=rhs.first;lhs.second+=rhs.second;return lhs;}template<class A,class B>_1b std::pair<A,B>&operator-=(std::pair<A,B>&lhs,const std::pair<A,B>&rhs){lhs.first-=rhs.first;lhs.second-=rhs.second;return lhs;}template<class T>std::vector<T>&operator+=(std::vector<T>&a,const std::vector<T>&b){a.insert(a.end(),b.begin(),b.end());return a;}template<class T>std::vector<T>&operator+=(std::vector<T>&a,const T&b){a.insert(a.end(),b);return a;}template<class T>std::vector<T>&operator+=(std::vector<T>&a,T&&b){a.insert(a.end(),std::forward<T>(b));return a;}template<class T>std::vector<T>operator+(std::vector<T>a,const std::vector<T>&b){a+=b;return a;}template<class T>std::vector<T>operator+(std::vector<T>a,T&b){a+=b;return a;}template<class T>std::vector<T>operator+(std::vector<T>a,T&&b){a+=std::forward<T>(b);return a;}
#define M__AT_INIT(line, Pred) struct CM_INNER_ATINIT##line##_17 {   CM_INNER_ATINIT##line## _17 () Pred } CM_INNER_ATINIT##line
#define M_AT_INIT(line, Pred) M__AT_INIT(line, Pred)
#define AT_INIT(Pred) M_AT_INIT(__LINE__, Pred)
#define M__AT_EXIT(line, Pred) struct CM_INNER_ATEXIT##line##_17 {   ~CM_INNER_ATEXIT##line## _17 () Pred } CM_INNER_ATEXIT##line
#define M_AT_EXIT(line, Pred) M__AT_EXIT(line, Pred)
#define AT_EXIT(Pred) M_AT_EXIT(__LINE__, Pred)
#define CONSTRAINT(n, a, b) constexpr auto n = a;
#undef _1b
cm::scanner<cm::optimal_reader>sc(stdin);constexpr int MOD=1'000'000'007;struct point_t{long long x=0,y=0;point_t()=default;point_t(long long x,long long y):x(x),y(y){}};point_t operator+(const point_t&lhs,const point_t&rhs){return point_t(lhs.x+rhs.x,lhs.y+rhs.y);}point_t operator-(const point_t&lhs,const point_t&rhs){return point_t(lhs.x-rhs.x,lhs.y-rhs.y);}long long operator^(const point_t&lhs,const point_t&rhs){return lhs.x*rhs.y-lhs.y*rhs.x;}constexpr int N=1'000'005;point_t p[N],q[N];long long f[N],g[N];int n,ans;int main(){n=sc.next_int();for(int i=1;i<=n;i++){p[i].x=sc.next_int();p[i].y=sc.next_int();q[i]=q[i-1]+p[i];q[i].x%=MOD;q[i].y%=MOD;}for(int i=2;i<=n;i++){f[i]=f[i-1]+(p[i-1]^p[i]);g[i]=(g[i-1]+f[i])%MOD;}f[n+1]=f[n]+(p[n]^p[1]);for(int i=3,j=1;i<=n;i++){while(j<i-1&&std::abs(f[n+1])<std::abs((f[i]-f[j])+(p[i]^p[j]))*2.0L)j++;ans=(ans+f[i]%MOD*(i-j-1)-(g[i-2]-g[j-1])+(p[i]^(q[i-2]-q[j-1])))%MOD;ans=(ans+(f[n+1]-f[i])%MOD*(j-1)+g[j-1]-(p[i]^q[j-1]))%MOD;}ans=(ans+MOD)*2ll%MOD;ans=(ans+std::abs(f[n+1])%MOD*(n*(n-3ll)/2%MOD))%MOD;printf("%d\n",ans);return 0;}