var n:integer;
begin
read (n);
if n=1 then write ('Washington');
if n=2 then write ('Adams');
if n=3 then write ('Jefferson');
if n=4 then write ('Madison');
if n=5 then write ('Monroe');
if n=6 then write ('Adams');
if n=7 then write ('Jackson');
if n=8 then write ('Van Buren');
if n=9 then write ('Harrison');
if n=10 then write ('Tyler');
if n=11 then write ('Polk');
if n=12 then write ('Taylor');
if n=13 then write ('Fillmore');
if n=14 then write ('Pierce');
if n=15 then write ('Buchanan');
if n=16 then write ('Lincoln');
if n=17 then write ('Johnson');
if n=18 then write ('Grant');
if n=19 then write ('Hayes');
if n=20 then write ('Garfield');
if n=21 then write ('Arthur');
if n=22 then write ('Cleveland');
if n=23 then write ('Harrison');
if n=24 then write ('Cleveland');
if n=25 then write ('McKinley');
if n=26 then write ('Roosevelt');
if n=27 then write ('Taft');
if n=28 then write ('Wilson');
if n=29 then write ('Harding');
if n=30 then write ('Coolidge');
if n=31 then write ('Hoover');
if n=32 then write ('Roosevelt');
if n=33 then write ('Truman');
if n=34 then write ('Eisenhower');
if n=35 then write ('Kennedy');
if n=36 then write ('Johnson');
if n=37 then write ('Nixon');
if n=38 then write ('Ford');
if n=39 then write ('Carter');
if n=40 then write ('Reagan');
end.