namespace Solution {
    open Microsoft.Quantum.Intrinsic;
 
    operation Solve (x : Qubit[], y : Qubit) : Unit is Adj+Ctl {
        let n = Length(x);
		if (n == 1) {
			X(x[0]);
			(Controlled X)(x, y);
			X(x[0]);
		}
		if (n == 2) {
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
		}
		if (n == 3) {
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
		}
		if (n == 4) {
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
		}
		if (n == 5) {
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
		}
		if (n == 6) {
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
		}
		if (n == 7) {
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			X(x[6]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			X(x[6]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
		}
		if (n == 8) {
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			X(x[6]);
			X(x[7]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			X(x[6]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			X(x[6]);
			X(x[7]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			X(x[6]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			X(x[5]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			X(x[3]);
			X(x[4]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			X(x[2]);
			X(x[3]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[2]);
			(Controlled X)(x, y);
			X(x[0]);
			X(x[1]);
			(Controlled X)(x, y);
		}
    }
}