#include <bits/stdc++.h>

#ifndef LOCAL
#define cerr dolor_sit_amet
#endif

#define mp make_pair
#define sz(x) ((int)((x).size()))
#define X first
#define Y second
#define ALL(x) (x).begin(), (x).end()

using namespace std;
typedef long long ll;
typedef unsigned long long ull;
typedef long double ld;
typedef pair < int , int > ipair;
typedef pair < ll , ll > lpair;
const int IINF = 0x3f3f3f3f;
const ll LINF = 0x3f3f3f3f3f3f3f3fll;
const double DINF = numeric_limits<double>::infinity();
const int MOD = 1000000007;
const double EPS = 1e-9;
const int DX[] = { 1,  0, -1,  0,  1, -1,  1, -1};
const int DY[] = { 0,  1,  0, -1,  1, -1, -1,  1};
ll gcd(ll a, ll b) { return b ? gcd(b, a % b) : a; }
ll sqr(ll x) { return x*x; } ll sqr(int x) { return (ll)x*x; }
double sqr(double x) { return x*x; } ld sqr(ld x) { return x*x; }
mt19937 mmtw(960172);
ll rnd(ll x, ll y) { static uniform_int_distribution<ll> d; return d(mmtw) % (y - x + 1) + x; }

// ========================================================================= //

string best[256] = {
    "!x&x",
    "!(x|y|z)",
    "!x&!y&z",
    "!x&!y",
    "!x&!z&y",
    "!x&!z",
    "!(!y&!z|x|y&z)",
    "!(x|y&z)",
    "!x&y&z",
    "!(!y&z|!z&y|x)",
    "!x&z",
    "!(!z&y|x)",
    "!x&y",
    "!(!y&z|x)",
    "!x&(y|z)",
    "!x",
    "!y&!z&x",
    "!y&!z",
    "!(!x&!z|x&z|y)",
    "!(x&z|y)",
    "!(!x&!y|x&y|z)",
    "!(x&y|z)",
    "!(!x&!y|x&y|z)|!x&!y&z",
    "!((x|y)&z|x&y)",
    "!x&y&z|!y&!z&x",
    "!x&y&z|!y&!z",
    "!x&z|!y&!z&x",
    "!x&z|!y&!z",
    "!x&y|!y&!z&x",
    "!x&y|!y&!z",
    "!x&(y|z)|!y&!z&x",
    "!x|!y&!z",
    "!y&x&z",
    "!(!x&z|!z&x|y)",
    "!y&z",
    "!(!z&x|y)",
    "!x&!z&y|!y&x&z",
    "!x&!z|!y&x&z",
    "!x&!z&y|!y&z",
    "!x&!z|!y&z",
    "!x&y&z|!y&x&z",
    "!(!x&z|!z&x|y)|!x&y&z",
    "!(x&y)&z",
    "!(!z&x|y)|!x&z",
    "!x&y|!y&x&z",
    "!(!y&z|x)|!y&x&z",
    "!x&y|!y&z",
    "!x|!y&z",
    "!y&x",
    "!(!x&z|y)",
    "!y&(x|z)",
    "!y",
    "!x&!z&y|!y&x",
    "!x&!z|!y&x",
    "!x&!z&y|!y&(x|z)",
    "!x&!z|!y",
    "!x&y&z|!y&x",
    "!(!x&z|y)|!x&y&z",
    "!x&z|!y&x",
    "!x&z|!y",
    "!x&y|!y&x",
    "!(!x&!y&z|x&y)",
    "!x&(y|z)|!y&x",
    "!x|!y",
    "!z&x&y",
    "!(!x&y|!y&x|z)",
    "!x&!y&z|!z&x&y",
    "!x&!y|!z&x&y",
    "!z&y",
    "!(!y&x|z)",
    "!x&!y&z|!z&y",
    "!x&!y|!z&y",
    "!x&y&z|!z&x&y",
    "!(!x&y|!y&x|z)|!x&y&z",
    "!x&z|!z&x&y",
    "!(!z&y|x)|!z&x&y",
    "!(x&z)&y",
    "!(!y&x|z)|!x&y",
    "!x&z|!z&y",
    "!x|!z&y",
    "!z&x",
    "!(!x&y|z)",
    "!x&!y&z|!z&x",
    "!x&!y|!z&x",
    "!z&(x|y)",
    "!z",
    "!x&!y&z|!z&(x|y)",
    "!x&!y|!z",
    "!x&y&z|!z&x",
    "!(!x&y|z)|!x&y&z",
    "!x&z|!z&x",
    "!(!x&!z&y|x&z)",
    "!x&y|!z&x",
    "!x&y|!z",
    "!x&(y|z)|!z&x",
    "!x|!z",
    "!y&x&z|!z&x&y",
    "!(!x&y|!y&x|z)|!y&x&z",
    "!y&z|!z&x&y",
    "!(!z&x|y)|!z&x&y",
    "!y&x&z|!z&y",
    "!(!y&x|z)|!y&x&z",
    "!y&z|!z&y",
    "!(!y&!z&x|y&z)",
    "!x&y&z|!y&x&z|!z&x&y",
    "!(!x&y|!y&x|z)|!x&y&z|!y&x&z",
    "!(x&y)&z|!z&x&y",
    "!(!z&x|y)|!x&z|!z&x&y",
    "!(x&z)&y|!y&x&z",
    "!(!y&x|z)|!x&y|!y&x&z",
    "!(x&y)&z|!z&y",
    "!x|!y&z|!z&y",
    "!(y&z)&x",
    "!(!x&y|z)|!y&x",
    "!y&z|!z&x",
    "!y|!z&x",
    "!y&x|!z&y",
    "!y&x|!z",
    "!y&(x|z)|!z&y",
    "!y|!z",
    "!(y&z)&x|!x&y&z",
    "!(!x&y|z)|!x&y&z|!y&x",
    "!(x&y)&z|!z&x",
    "!x&z|!y|!z&x",
    "!(x&z)&y|!y&x",
    "!x&y|!y&x|!z",
    "!x&y|!y&z|!z&x",
    "!(x&y&z)",
    "x&y&z",
    "!(x|y|z)|x&y&z",
    "!x&!y&z|x&y&z",
    "!x&!y|x&y&z",
    "!x&!z&y|x&y&z",
    "!x&!z|x&y&z",
    "!(!y&!z|x|y&z)|x&y&z",
    "!(x|y&z)|x&y&z",
    "y&z",
    "!(x|y|z)|y&z",
    "!x&z|y&z",
    "!x&!y|y&z",
    "!x&y|y&z",
    "!x&!z|y&z",
    "!x&(y|z)|y&z",
    "!x|y&z",
    "!y&!z&x|x&y&z",
    "!y&!z|x&y&z",
    "!(!x&!z|x&z|y)|x&y&z",
    "!(x&z|y)|x&y&z",
    "!(!x&!y|x&y|z)|x&y&z",
    "!(x&y|z)|x&y&z",
    "!(!x&!y|x&y|z)|!x&!y&z|x&y&z",
    "!((x|y)&z|x&y)|x&y&z",
    "!y&!z&x|y&z",
    "!y&!z|y&z",
    "!x&z|!y&!z&x|y&z",
    "!(x&z|y)|y&z",
    "!x&y|!y&!z&x|y&z",
    "!(x&y|z)|y&z",
    "!x&(y|z)|!y&!z&x|y&z",
    "!x|!y&!z|y&z",
    "x&z",
    "!(x|y|z)|x&z",
    "!y&z|x&z",
    "!x&!y|x&z",
    "!x&!z&y|x&z",
    "!x&!z|x&z",
    "!x&!z&y|!y&z|x&z",
    "!(x|y&z)|x&z",
    "(x|y)&z",
    "!(x|y|z)|(x|y)&z",
    "z",
    "!x&!y|z",
    "!x&y|x&z",
    "!(!y&z|x)|x&z",
    "!x&y|z",
    "!x|z",
    "!y&x|x&z",
    "!y&!z|x&z",
    "!y&(x|z)|x&z",
    "!y|x&z",
    "!x&!z&y|!y&x|x&z",
    "!(x&y|z)|x&z",
    "!x&!z&y|!y&(x|z)|x&z",
    "!x&!z|!y|x&z",
    "!y&x|y&z",
    "!(!x&z|y)|y&z",
    "!y&x|z",
    "!y|z",
    "!x&y|!y&x|x&z",
    "!x&!z|!y&x|y&z",
    "!x&y|!y&x|z",
    "!x|!y|z",
    "x&y",
    "!(x|y|z)|x&y",
    "!x&!y&z|x&y",
    "!x&!y|x&y",
    "!z&y|x&y",
    "!x&!z|x&y",
    "!x&!y&z|!z&y|x&y",
    "!(x|y&z)|x&y",
    "(x|z)&y",
    "!(x|y|z)|(x|z)&y",
    "!x&z|x&y",
    "!(!z&y|x)|x&y",
    "y",
    "!x&!z|y",
    "!x&z|y",
    "!x|y",
    "!z&x|x&y",
    "!y&!z|x&y",
    "!x&!y&z|!z&x|x&y",
    "!(x&z|y)|x&y",
    "!z&(x|y)|x&y",
    "!z|x&y",
    "!x&!y&z|!z&(x|y)|x&y",
    "!x&!y|!z|x&y",
    "!z&x|y&z",
    "!(!x&y|z)|y&z",
    "!x&z|!z&x|x&y",
    "!x&!y|!z&x|y&z",
    "!z&x|y",
    "!z|y",
    "!x&z|!z&x|y",
    "!x|!z|y",
    "(y|z)&x",
    "!(x|y|z)|(y|z)&x",
    "!y&z|x&y",
    "!(!z&x|y)|x&y",
    "!z&y|x&z",
    "!(!y&x|z)|x&z",
    "!y&z|!z&y|x&y",
    "!x&!y|!z&y|x&z",
    "(x|y)&z|x&y",
    "!(x|y|z)|(x|y)&z|x&y",
    "x&y|z",
    "!x&!y|x&y|z",
    "x&z|y",
    "!x&!z|x&z|y",
    "y|z",
    "!x|y|z",
    "x",
    "!y&!z|x",
    "!y&z|x",
    "!y|x",
    "!z&y|x",
    "!z|x",
    "!y&z|!z&y|x",
    "!y|!z|x",
    "x|y&z",
    "!y&!z|x|y&z",
    "x|z",
    "!y|x|z",
    "x|y",
    "!z|x|y",
    "x|y|z",
    "!x|x"
};
int main() {
    ios::sync_with_stdio(false);


    int n;
    scanf("%d", &n);
    for (int i = 0; i < n; ++i) {
        char q[10];
        scanf("%s", q);
        int x = 0;
        for (int j = 0; j < 8; ++j)
            if (q[j] == '1')
                x |= 1 << j;
        std::cout << best[x] << "\n";
    }

    return 0;
}