#include "bits/stdc++.h"

using namespace std;

int main() {
	//freopen("input.txt", "rt", stdin);
	//freopen("output.txt", "wt", stdout);
	/*string s;
	getline(cin, s);
	for (auto& c: s) {
		c = c ? 'a' : 'b';
	}
	cout << s << endl;*/
	/*for (int i = 63; i >= 0; --i) {
		for (int j = i * 64; j < (i + 1) * 64; ++j) {
			cout << s[j];
		}
		cout << endl;
	}*/
	string s = "aaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbaaaabbbbaaaabaaaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbababbbbabbabbababbaabbbbbbbbbbbbaaaaaaaaaaaaaaaaaaabbbbbbbbbabbaaaababaaaaaabaaaababbbbbbbbbbbbbbaaaaaaaaaaaaaaaaabbbbbbbbbaaabbbbaaabbbabbabbbbabbbbabbbbbbbbbbbbaaaaaaaaaaaaaaabbbbbbbbbaabbbaababaaabbbaaababbbaabaaabbbbbbbbbbbaaaaaaaaaaaaaabbbbbbbbbabbaaabbbbbabbababaaababbaaabbbbbbbbbbbbbaaaaaaaaaaaaabbbbbbbbaaaabbabbabaaaabaaababaaaabbbabaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbbabaabaabaaababbbbabbbabbabaaaaabaaabbbbbbbbbaaaaaaaaaabbbbbbbabaabbbbabbbbabbbaabbbaaaabbbabbbbbababbbbbbbbbaaaaaaaaabbbbbbbbaaabbaaaaabaaaaaaabbaaabbaaaaaababaabbbabbbbbbbbaaaaaaabbbbbbbabababaababaaabbababbaababaababbaaabbaaaaababbbbbbbaaaaaabbbbbbbaaabaaabbbbbbbbbbbaababbbbbbbbbbbabbbbbabaaaabbbbbbaaaaaabbbbbbbababbbbbbbbbbbbbbbbaaabbbbbbbbbbbbbbbbbbbbbabbbbbbbaaaaabbbbbbbaabbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaabbbbbbbbbbbbbbbbbbbbbbbbaaabaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaabbbbbbbbbbbbbbbbbbbbbbbbbabaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbbbbbbbbbbbbabaababbbbbbbbbbbbbbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbaabbbbbbbbbbbbbbbbaabaaaabbbbbababbbbbbbbbbbaaabaabbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbaaababbbbbbaaaaabbbbbbbaaabaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaabbbaaababbabbabbabbaababbbabaabaabbbbbbbbbbbbbbbbbbbbbbbbbabaabaaabbbaaabbbbaaabaabbaaaabaabbaaabbbbbbbbbbbbbbbbbbbbbbbbbaaaabbbbabababababbbbabbabaababbbaabbbaaabbbbbbbbbbbbbbbbbbbbbbbbbabbabaaaababaaaababaabababbabaaabbabbabbbbbbbbbbbbbbbbbbbbbbbbbaaaaabbabbbabbabbbabbaaaaabaabbabbaabaaababbbbbbbbbbbbbbbbbbbbaaabbbaabaabaaabbbabaabbbabbbbaababbbaaabaaabbbbbbbbbbbbbbbbbbbbbabbabbbbabbabbbaaababbbaaaaabbbbababbbbbbabbbbbbbbbbbbbbbbbbbbbaaaaabaabaabbbabbbaaabababbabbabaabaaabaabaabbbbbbbbbbbbbbbbbbbbabbbbbbabbbbaaaabaababaaaababaababbbbaaabbbabbbbbbbbbbbbbbbbbbbbaaabaababbabbbabbbabbbbababbbabbbbaabbbaaababbbbbbbbbbbbbbbbbbbbbabbbabaabaabaaabaabbbbbbaabaabaaaabbabbbaaabbbbbbbbbabbbbbbbbbaaaaabaaabbbabbbaaabbbbbbbbababbbbbabaaabaababbbbbbbbaabbbbbbbbbbbbabbabbbaaaaabbbaabbbbbbbaaabaabaaaabbbabbbbbbbbbbbaabbbbbbbbbaaaaabaabaabbabbaaabbbbbbbbbabbabbbbbaabaaaabbbbbbbbbaabbbbbbbaaaaabaaabbbaabbbaabbbbbbbbbbbabaabaaabbaaaaaaaaabbbbbbaaabbbbaaaaabbbbbaaabbabaaabbbbbbbbbbbbbbbabbabbaababbaaaaaaabbaaaabbaaaaabbbbbbbbbaabaaabbbbbbbbbbbbbbbabaaaaaaabbbbbbbbaaaaaaaaaaaaaaabbbbbbbbbbbbaaabaabbbbbbbbbbbbbbaaabababbbbbbbbbbbbbaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbabbbbbbbaabbbbaabbbbbbbbbbaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbaaaabaaaaabaaababbaabbabbabaabbbaaaaaaaaaaaaaaaaaaaaabbbbbbabbabbabbbabbbabbbaaaabbaabaabaaabbbaaaaaaaaaaaaaaaaaaaaaaaabbbaabaabaaaaaababaaabbbbaabbabbabbabbaaaaaaaaaaaaaaaaaaaaaaaaaaabaabbabbbbbabbbabbbabaababbaaabaababaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbaaaaaababaaaaabbbbaaaababababbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbabababbbbbaaaabbbbababbbabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbabaaabaaabbabaaaabaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaababbbabababaababbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabababbbbbbabaaaaaaaaaaaaaaaaaaaaaaaaaa";
	int a, b;
	cin >> a >> b;
	a = 63 - a;
	if (s[a * 64 + b] == 'a') {
		cout << "OUT" << endl;
	} else {
		cout << "IN" << endl;
	}
}