#include<cmath>
#include<math.h>
#include<ctype.h>
#include<algorithm>
#include<bitset>
#include<cassert>
#include<cctype>
#include<cerrno>
#include<cfloat>
#include<ciso646>
#include<climits>
#include<clocale>
#include<complex>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<ctime>
#include<cwchar>
#include<cwctype>
#include<deque>
#include<exception>
#include<fstream>
#include<functional>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<iterator>
#include<limits>
#include<list>
#include<locale>
#include<map>
#include<memory>
#include<new>
#include<numeric>
#include<ostream>
#include<queue>
#include<set>
#include<sstream>
#include<stack>
#include<stdexcept>
#include<streambuf>
#include<string>
#include<typeinfo>
#include<utility>
#include<valarray>
#include<vector>
#include<string.h>
#include<stdlib.h>
#include<stdio.h>
using namespace std;
int main()
{
    long long i,j,k,l,a,b,c,o,p,q;
    cin>>a>>b>>c;
    if(a==0||b==0||c==0){
                         cout<<a/3+b/3+c/3<<endl;
                         return 0;
    }
    o=a%3;
    if(o==0)o=3;
    p=b%3;
    if(p==0)p=3;
    q=c%3;
    if(q==0)q=3;
    k=(a+b+c-o-p-q)/3;
    k+=max(min(o,min(p,q)),o/3+p/3+q/3);
    cout<<k<<endl;                     
  //  system("pause");
    return 0;
}