sm = '''YYYYYYYYYYYYYYYYYYYYYYYYYY#Y#Y######Y#YYYYYYYYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYYYY#Y###Y#Y#Y#YY#Y#####YYYYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYY###Y#YYY#YYY##Y#YYYY#YY#YYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYY####Y#Y#Y#####YYYY####Y#Y###Y#YYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYY##YYYYYY#Y#YYYYY####YYYY#Y#Y#Y##YYYYYYYYYYYYYYYY
YYYYYYYYYYYYYY#YY##Y#####Y###Y###Y#YY#Y##YYY#YY#Y#YYYYYYYYYYYYYY
YYYYYYYYYYYYY###YY#YY#YYYYYY#Y#YYY####YY##Y##Y##Y##YYYYYYYYYYYYY
YYYYYYYYYYY######Y##Y##Y###Y###Y###YYYY##YY#YY#YYY###YYYYYYYYYYY
YYYYYYYYYY############YYYY#YYYYY#YYY#Y##YY##Y##Y#YY###YYYYYYYYYY
YYYYYYYYY####################Y#######YY####YY##########YYYYYYYYY
YYYYYYYY################################################YYYYYYYY
YYYYYYY##################################################YYYYYYY
YYYYYYY##################################################YYYYYYY
YYYYYY####################################################YYYYYY
YYYYY######################################################YYYYY
YYYYY######################################################YYYYY
YYYY########################################################YYYY
YYY##########################################################YYY
YYYYY########################################################YYY
YYYYYYY############YYY#YY##############YYY#Y#Y#############YYYYY
YY##YYYYY#########YY#YYY###############Y#YYYYYYY########YYYYYYYY
YY####YYYYY#####YYY##Y#YYY###############Y##Y##YY#Y##YYYYYYY##YY
Y#######YYYYY#YYY###YY###YY###########Y#YY#YYY##YYYYYYYYY######Y
Y#########YYYYY#YY#YY##Y##YYY#########Y##Y#####YY#YYYY#########Y
Y############Y##Y###YYYYY###YY#######YYY#YY#YYYY###Y###########Y
Y#########YYYYY#YYY###Y###YYY########Y#Y#####Y#YYY#YY#Y########Y
############Y###Y#YY#YY#YYY#YY######YY#YY#YYYY##Y###YYY#########
###########YYY#YY#Y##Y###Y###Y####Y#Y###Y####YY###YYY#Y#########
###########Y######Y####YYYY#YY#Y#YYYY#Y#YY#Y####YYY###Y#########
###########YYYYY#YY#YY###Y###YYY#Y#Y##Y##Y#YY#YYY#YY#YY#########
############Y##Y####Y##Y###YYY#Y###YYYYY####Y#Y######Y##########
###########YYY###YY#YY#YYY###Y#YY###Y####YY#Y###YYY#YYY#########
#############YYYYY##Y###Y##Y###Y##YYYYY#YY##Y##YY#YYY#Y#########
##############Y##Y#YYYY#Y#YYYY#Y#YY#Y#Y##Y#YYY##Y##Y############
############YYYY####Y#Y#Y#Y#Y####Y##Y#YY#Y###YY###YYY###########
#############Y#YY#YYY###YYY####YYY#YY##YYYY#YY##YYY#############
################YYY###YYY#Y##Y##Y##Y##YY#Y###Y#YY#YY############
##################YYY#Y######YYYYY#######YYY#YYY################
Y################YY#YYYY#####Y#Y###########YYY#YY##############Y
Y##############################YYYY############################Y
Y###########################Y#YY#Y#############################Y
Y#########################Y#YYY################################Y
YY########################YYY#YYY#############################YY
YY#######YY###################Y###############################YY
YYY#######Y#Y################YYY#####################Y#######YYY
YYY#######YYY#YYY###########YY#Y###########Y#####Y#YYYY######YYY
YYY#######Y#Y#Y#YY#Y#YYY##Y#Y##YY#Y#YY#Y##YYY##YYYYY#Y#######YYY
YYYY########YYY##YYYYY#YYYYYYY##YYY##YYYYYY#Y#YY###Y########YYYY
YYYYY#######Y#YY####Y####Y###YY###YYYY###Y#####Y#Y#########YYYYY
YYYYY##########Y#YY#YY#YYY#Y####Y###Y##Y#YYYYY#YYY#########YYYYY
YYYYYY########YYYY##Y##Y#YYYY#YYY#Y#YYYY###Y#YYY##########YYYYYY
YYYYYYY#########Y##YYY#####Y##Y#Y#YYY#Y##YYY#############YYYYYYY
YYYYYYY#########YY###YY#Y#YYY###YYY#Y###YY#YYY###########YYYYYYY
YYYYYYYY#########YYY####YYY###Y##Y####Y####Y############YYYYYYYY
YYYYYYYYY#########Y##YYYY#Y#YYYYYY#YYYY#Y##############YYYYYYYYY
YYYYYYYYYY############Y#Y####Y##Y##Y#Y##YY############YYYYYYYYYY
YYYYYYYYYYY#############YYYY####YYYY#YYYY############YYYYYYYYYYY
YYYYYYYYYYYYY####################Y#################YYYYYYYYYYYYY
YYYYYYYYYYYYYY####################################YYYYYYYYYYYYYY
YYYYYYYYYYYYYYYY################################YYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYY##############################YYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYY########################YYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYYYY####################YYYYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYYYYYYYY############YYYYYYYYYYYYYYYYYYYYYYYYYY'''.split('\n')

x,y = map(int, input().split())
print ("IN" if sm[x][y]!='Y' else "OUT")