#include<stdio.h>
int n,m,i,j,x,a[10010],ca,b[10010],cb,ax,bx,t,t2,p1,p2,S;
__int64 Res;
bool d;
char p[101][10010];
int main()
{
	scanf("%d%d",&n,&m);
	for(i=1;i<=n;i++){
		scanf("%s",p[i]+1);
		p[i][0]=p[i][m+1]='#';
	}
	x=1;
	for(i=1;i<n;i++){
		S=0;
		if(p[i+1][x]=='.'){
			Res++;
			continue;}
		ax=0,bx=m+1;
		ca=cb=0;
		for(j=x-1;j>=1;j--){
			if(p[i][j]=='#')break;
			if(!ax&&p[i+1][j]=='.')ax=j;
			if(p[i][j]=='+')a[++ca]=j;
		}
		t=j;
		for(j=x+1;j<=m;j++){
			if(p[i][j]=='#')break;
			if(bx==m+1&&p[i+1][j]=='.')bx=j;
			if(p[i][j]=='+')b[++cb]=j;
		}
		t2=j;
		if(ca<=cb){for(j=ca+1;j<=cb+1;j++)a[j]=t;ca=cb+1;b[++cb]=t2;}
		else{for(j=cb+1;j<=ca+1;j++)b[j]=t2;cb=ca+1;a[++ca]=t;}
		if(ax==0&&bx==m+1)break;
		p1=p2=1;
		while(1){
			if(d==0){
				if(b[p2]>bx){
					S+=bx-x;
					x=bx;
					break;
				}
				else{
					d=1;
					S+=b[p2]-x;
					x=b[p2]-1;
					p2++;
				}
			}
			if(d==1){
				if(a[p1]<ax){
					S+=x-ax;
					x=ax;
					break;
				}
				else{
					d=0;
					S+=x-a[p1];
					x=a[p1]+1;
					p1++;
				}
			}
		}
		Res+=S;
		Res++;
	}
	if(i!=n){
		printf("Never\n");
		return 0;
	}
	printf("%I64d\n",Res);
}