/*
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NN&&OOOOTTTTiiTTTTTT@@@@PPcciiTTTT11OOOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NN&&PPTTiiTTTTTTTTTTTTTTTTTT@@@@TTPPTTTTTTTTTTTTiiTTTTOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOffTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTiiPPTTTTTTTTTTTTTTTTTTTTii55NN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTlliiTTTTTTTTTTTTTTTTTTTTTTTTiiOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&ffTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@mmiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTaaccTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTiiaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTiiaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTffNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTlliiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaa@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@aaiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTccNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTPPccTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTRR@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NN77TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTZZTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaa@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTiiPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@aaZZaaVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNiiTTiiaaPPaaVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@NNTTNN@@NNTTTTTTTTTTTTaaVVPPVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTaaccTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTPPVVPPaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTiiVVTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTPPPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTiiaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTPPTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaPPaaaaiiTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTOOTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaPPaaaaTTiiTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTaaTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaPPaaPPii@@@@TTTTTTTTTTTTTTTTTTTTTTTTaaccTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTOOTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTiiTTOO&&NN@@@@@@@@@@@@OOOOOO77TTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTPPTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPUU@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&aaTTTTTTTTTTaaTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTPPTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNeeTTTTTTffiiTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTPPTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTaaOOOOOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOOOOeeiiTTaaTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNiiTTTTTTTTTTPPOOTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTT&&ccaaffTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNiiTTTTii55NNTTTTPPOOOOOOTTTTTTPP@@@@@@@@@@@@@@@@@@@@OOTTTTTTOOOOOOPPTTTTNNeeaaTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTNN@@TTTTOO@@@@@@@@@@OOPPTTPPNN@@@@@@@@@@@@NNPPTTTTOO@@@@@@@@@@OOTTPP@@@@PPTTNN@@NNTTTTTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNNN@@NNTTPP@@@@@@@@@@@@@@@@OOTTTTOO@@@@@@@@OOTTTTPP@@@@@@@@@@@@@@@@PPTTNN@@NNNN@@NNTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTPPOO@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@OOTTOO@@@@@@@@@@@@@@@@@@NNTTTTPP@@@@PPTTTTNN@@@@@@@@@@@@@@@@@@OOTTOO@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@OOTT@@@@@@@@@@@@@@@@@@@@@@@@PPTTPPPPTTTTNN@@@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPP@@@@@@@@@@PPTT@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@TTPP@@@@@@@@OOTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTOO@@@@@@@@@@TTTT@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@TTTT@@@@@@@@@@PPTTTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTPPOOOOOOOOOOOONN@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOOOOOOOTTTTTTTTTTTTTTTTOOOOOOOO@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOOOOOOOOOOOOO@@@@@@@@
@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTT@@@@@@@@@@@@TTTT@@@@@@@@@@@@@@@@@@@@@@@@PPTTPPPPTTPP@@@@@@@@@@@@@@@@@@@@@@@@TTTT@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOONNTTTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@NNTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@NNTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTNN@@@@@@@@@@@@OOTT@@@@@@@@@@@@@@@@@@@@@@OOTTTTNN@@PPTTOO@@@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@@@@@NNTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@PPTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTPP@@@@@@@@@@@@@@OOTT@@@@@@@@@@@@@@@@@@@@NNTTTTNN@@@@NNTTTTNN@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTNN@@@@@@@@@@@@@@OOTTNN@@@@@@@@@@@@@@@@@@TTTTNN@@@@@@@@NNTTTT@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@@@@@@@NNTTTTTTTTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@OOTTPP@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@PPTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@TTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@TTPP@@@@@@OOOOOOPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOOOOOOO@@@@@@OOTT@@@@@@@@@@@@@@@@@@NNTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
OOTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@TTTTPPTTTTTTTTTTTTTTTTTTPPOOOOOOOOOOOOPPTTTTTTTTTTTTTTTTTTPPTTTT@@@@@@@@@@@@@@@@@@@@TTTTTTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
OOTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@NNOOTTTTTTTTTTOOOOOO@@PPTTNN@@@@@@@@@@@@@@@@@@@@NNTTPP@@OOOOOOTTTTTTTTTTOONN@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTPPTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@PPTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@PPTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
PPTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@OOTTTTTTTTPPTTOO@@@@@@@@OOTTPP@@@@@@@@@@@@@@@@@@@@@@@@PPTTOO@@@@@@@@OOTTPPTTTTTTTTOO@@@@@@@@@@NNTTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTOOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@
TTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@OOTTTTTTPPNN@@@@TTTT@@@@@@NNTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTNN@@@@@@PPTT@@@@NNPPTTTTTTOO@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTOOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@PPTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTPPNN@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@
TTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@NNPPTTTTOO@@@@@@@@@@PPTTNN@@@@PPTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTPP@@@@NNTTPP@@@@@@@@@@OOTTTTPPNN@@@@TTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTOOTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOONNTTTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@
TTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@NNTTTTPPNN@@@@@@@@@@@@OOTTOO@@NNTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTNN@@OOTTOO@@@@@@@@@@@@NNPPTTTTNN@@OOTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPNN@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@
TTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOONNTTTTPP@@@@@@@@@@@@@@@@@@TTTT@@PPTTNN@@@@@@@@@@@@NN&&&&NN@@@@@@@@@@@@NNTTPP@@TTTT@@@@@@@@@@@@@@@@@@PPTTTTNNOOPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTNNOOTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTPPOOOOOOOOOONN@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOOOOOOOOOOONN@@@@@@@@
TTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOPPTTPP@@@@@@@@@@@@@@@@@@@@OOTTPPTTPP@@@@@@@@@@@@aaTTTTTTTTPP@@@@@@@@@@@@PPTTPPTTOO@@@@@@@@@@@@@@@@@@@@PPTTPPOOOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTT@@OOTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@NNTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@NNTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTTT@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTNN@@@@@@@@@@NNTTTTTTTTTTTTNN@@@@@@@@@@NNTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTOOPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOPPTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@&&TTTTTTTTTTTTOO@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTOONN@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@OOTTTTTTTTTTTTOO@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNTTTT@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTNN@@@@@@@@@@NNTTTTTTTTTTiiNN@@@@@@@@@@NNTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@TTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@PPTTPP@@@@@@@@@@@@@@@@@@@@PPTTPPTTTT@@@@@@@@@@@@NNTTTTTTTTNN@@@@@@@@@@@@PPTTOOTTOO@@@@@@@@@@@@@@@@@@@@PPTTPPOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOOO@@TTTTPP@@@@@@@@@@@@@@@@@@TTTT@@PPTTOO@@@@@@@@@@@@@@OO&&@@@@@@@@@@@@@@NNTTPP@@TTTT@@@@@@@@@@@@@@@@@@PPTTTT@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTPPOOOOTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPOO@@NNTTTTPPNN@@@@@@@@@@@@OOTTOO@@NNTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTNN@@OOTTOO@@@@@@@@@@@@NNPPTTTTNN@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTNN@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTT@@@@@@PPTTTTOONN@@@@@@@@PPTTNN@@@@PPTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTPP@@@@@@TTPP@@@@@@@@NNOOTTTTPP@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@NNPPTTTTPPOO@@@@TTPP@@@@@@@@TTTTNN@@@@@@@@@@@@@@@@@@@@@@@@NNTTTT@@@@@@@@PPTT@@@@OOPPTTTTPPNN@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@
OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTTTNN@@@@@@@@@@NNPPTTTTTTTTTTOO@@@@@@@@NNTTPP@@@@@@@@@@@@@@@@@@@@@@@@PPTTNN@@@@@@@@OOTTTTTTTTTTPPNN@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTT@@@@@@NNTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTPPOOOOOOOOOOOONN@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTOOPPTTTTTTTTTTTTTT@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOOOOOOOOOOOOOO@@@@@@@@
OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@OOPPTTTTTTTTPPOOOONNPPTTOO@@@@@@@@@@@@@@@@@@@@OOTTPPNNOOOOPPTTTTTTTTPPOO@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTTTTT@@@@@@@@@@@@@@@@@@@@TTTTOOPPTTTTTTTTTTTTTTTTTTTTPPOOOOPPTTTTTTTTTTTTTTTTTTTTPPOOTTTT@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@OOOOOOPPTTTTTTTTTTTTTTTTTTTTTTTTOOOOOOOO@@@@@@@@OOTT@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTOO@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@PPTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@OOTTTTTTTTTTTTTT@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTTTTTTTPP@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@PPTTPP@@@@@@@@@@@@@@@@OOTTOO@@@@@@@@@@@@@@@@TTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@PPTTTTTTTTTTTTTT@@@@@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@OOTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@OOPPTTTTTTTTTTTTTTTTTTPPOO@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTT@@@@OOTTTTTTTTTTTTTTOO@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@
@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTNN@@@@@@@@@@@@@@OOTTNN@@@@@@@@@@@@@@@@@@TTTTOO@@@@@@@@NNTTPP@@@@@@@@@@@@@@@@@@NNTTOO@@@@@@@@@@@@@@OOTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@NNOOOOOOOOOOOOOO@@@@@@@@@@NNOOOOOOOOOOOOOO@@@@@@@@@@@@@@OOOOOOOOOOOOOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNOOOOOOOOOOOOOOOOOOOOOOOOOOOONN@@@@@@@@@@@@NNOOOOOOOOOOOOOO@@@@@@OOOOOOOOOOOOOONN@@@@@@@@@@@@@@@@@@@@OOOOOOOOOOOOOOOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNOOOOOOTTOOOOOONN@@@@@@@@@@@@@@@@@@@@@@NNOOOOOOOOOOOOOO@@@@@@OOOOOOOOOOOOOOOO@@@@@@@@@@@@NNOOOOOOOOOOOOOOOOOOOOOOOOOOOO@@@@@@@@
@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTTTTTTTTTTT@@@@@@@@@@@@@@OOTT@@@@@@@@@@@@@@@@@@@@NNTTTTNN@@@@NNTTTTNN@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@@@@@@@PPTTTTTTPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTOO@@@@@@@@@@@@PPTT@@@@@@@@@@@@@@@@@@@@@@NNTTTTNNNNTTTTNN@@@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@@@@@OOTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTNN@@@@@@@@@@TTTT@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@TTPP@@@@@@@@@@NNTTTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTPP@@@@@@@@@@TTTT@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@TTTT@@@@@@@@@@PPTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTPP@@@@@@@@TTTT@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@NNPPiiTTTTaaNN@@@@@@@@@@OOiiTTiiPPNN@@@@@@@@iiTTTTOO@@@@@@TTTTTTTTTTTTOO@@@@@@77TTTTTTOO&&TTTTOO@@@@@@@@88TTTTiiiiOO@@@@@@@@OOTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTii@@OOTTTT&&@@@@@@iiTTTTTTNN&&TTTTOO@@@@@@@@&&TTTTTTTT&&@@@@@@@@eeTTTTTT@@&&TTTTii@@@@@@@@@@&&TTTTTTTT@@@@@@@@@@OOTTTTTTTTTTTT77@@@@@@@@OOiiiiTTiiOO@@@@@@@@OOTTTTTTiiTT&&@@@@@@@@@@@@&&iiTTTTiiNN@@
@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTOO@@@@@@OOTT@@@@@@@@@@@@@@@@@@@@@@NNTTTTOOPPTTTTNN@@@@@@@@@@@@@@@@@@@@@@TTOO@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@aaTTTTTTTTTTPP@@@@@@@@PPTTTTTTTTTTTT@@@@@@@@iiTTTTOO@@@@@@iiTTTTTTTTTTOO@@@@@@iiTTTTTTOO&&TTTTOO@@@@@@NNTTTTTTTTTTTTNN@@@@@@OOTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTT&&OOTTTT&&@@@@@@TTTTTTTTOO&&TTTTOO@@@@@@NNiiTTTTTTTTTTOO@@@@@@OOTTTTTT@@OOTTTTTT@@@@@@@@@@OOTTTTTTii@@@@@@@@@@OOTTTTTTTTTTTTii@@@@@@NNTTTTTTTTTTTTOO@@@@@@OOTTTTTTTTTTTTPP@@@@@@@@OOTTTTTTTTTTTTOO
@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@OOTTOO@@@@@@@@@@@@@@@@@@OOTTTTNN@@@@OOTTTTOO@@@@@@@@@@@@@@@@@@OOTTOO@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@TTTTTTiiTTTTTT@@@@@@@@iiTTTTPPiiTTTTWW@@@@@@iiTTTTOO@@@@@@iiTTTTPPOOOONN@@@@@@iiTTTTTTii&&TTTTOO@@@@@@OOTTTTTTPPTTTTOO@@@@@@OOTTTTiiOOOOOO@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTOOOOTTTT&&@@@@@@TTTTTTTTPP&&TTTTOO@@@@@@OOTTTTiiiiTTTTPP@@@@@@&&TTTTii@@TTTTTTOO@@@@@@@@@@iiTTTTTTTT88@@@@@@@@NNOOaaTTTTTTOOmm@@@@@@&&TTTTiiPPTTTTTT@@@@@@OOTTTTTTaaTTTTTT@@@@@@@@PPTTTTiiiiTTTTTT
@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTNN@@NNNN@@NNTTTT@@@@@@@@@@@@@@@@PPTTTTNN@@@@@@@@NNTTTTPPNN@@@@@@@@@@@@@@TTTT@@@@&&NN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@&&TTTTTT&&TTTTTT@@@@@@@@TTTTTTOOTTTTTT&&@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTTTTT&&TTTTOO@@@@@@OOTTTTTTOOTTTTOO@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTiiOOTTTT&&@@@@@@TTTTTTTTTT&&TTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@OOTTTTii@@TTTTTTOO@@@@@@@@@@TTTTTTTTTT&&@@@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTTT@@@@@@OOTTTTTT&&TTTTTT@@@@@@@@iiTTTTOOTTTTTTTT
@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTNN@@NNTTTTNN@@PPTTPP@@@@@@@@NNOOTTTTPP@@@@@@@@@@@@@@NNPPTTTTPPNN@@@@@@@@PPTTPP@@PPTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@&&TTTTTTiiTTTTTT@@@@@@@@TTTTTTOOTTTTTT&&@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTTTTTiiTTTTOO@@@@@@OOTTTTTTOOTTTTOO@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTTTOOTTTT&&@@@@@@TTTTTTTTTTaaTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@NNTTTTTT@@iiTTTTOO@@@@@@@@@@TTTTTTTTTTOO@@@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTT&&TTTTTT@@@@@@@@TTTTTTPPTTTTTTTT
@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTTTNN@@NNTTTTTTPPNNmmTTTTTTOOOOTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTPPOOTTTTTTOOccTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTT@@@@@@@@TTTTTTOOTTiiiiUU@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTTTTTiiTTTTOO@@@@@@OOTTTTTTOOiiii&&@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTTTiiTTTT&&@@@@@@TTTTTTTTTTTTTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@iiTTTTUUiiTTTT&&@@@@@@@@NNTTTTTTTTTTVV@@@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTT&&TTTTTT@@@@@@@@PPTTTTiiTTTTTTTT
@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTaaiiaaTTTTTTTTTTPPOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOPPTTTTTTTTPPPPTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@iiTTTTiiaa@@@@@@@@@@@@TTTTTTOO@@@@@@@@@@@@@@iiTTTTOO@@@@@@iiTTTTPPOOOONN@@@@@@iiTTTTTTTTiiTTTTOO@@@@@@OOTTTTTT@@@@@@@@@@@@@@OOTTTTiiOOOONN@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTTTiiTTTT&&@@@@@@TTTTTTTTTTiiTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@TTTTTTOOTTTTTTWW@@@@@@@@&&TTTTTTTTTTTT@@@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTTPPTTTTPP@@@@@@@@OOTTTTTTiiNN@@@@
@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTOOTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTiiTT7788OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOOTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTiiNN@@@@@@@@@@TTTTTTOO@@@@@@@@@@@@@@iiTTTTOO@@@@@@iiTTTTTTTTTTOO@@@@@@iiTTTTTTTTiiTTTTOO@@@@@@OOTTTTTT@@@@@@@@@@@@@@OOTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTTTTTTTTT&&@@@@@@TTTTTTTTTTiiTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@iiTTTTffTTTTTT@@@@@@@@@@&&TTTTiiTTTTTT@@@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTTTTTTTT@@@@@@@@@@@@PPTTTTTTaa@@@@
@@@@@@@@@@@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTPPTTTTTTTT&&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO77TTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTiiNN@@@@@@@@TTTTTTOO@@@@@@@@@@@@@@iiTTTTOO@@@@@@iiTTTTiiiiiiOO@@@@@@iiTTTTTTTTTTTTTTOO@@@@@@OOTTTTTT@@@@@@@@@@@@@@OOTTTTTTiiiiOO@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTiiTTTTTTTT&&@@@@@@TTTTTTTTTTTTTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@77TTTTiiTTTTTT@@@@@@@@@@OOTTTT&&TTTTTT@@@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTTiiTTTTcc@@@@@@@@@@@@aaTTTTTTaa@@
@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTOOTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTT&&TTTTTTTTiiPP&&WW@@@@@@@@@@@@@@@@@@@@@@@@NN&&aaTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@NNOOOOffTTTTTTii@@@@@@@@TTTTTTOO&&&&&&NN@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTTTTTTTTTTTOO@@@@@@OOTTTTTTNN&&&&NN@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTTTTTTTTTTT&&@@@@@@TTTTTTffTTTTTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@OOTTTTiiTTTTii@@@@@@@@@@iiTTTTaaTTTTTTOO@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTT&&TTTTTT@@@@@@@@OOOOVVTTTTTTTT77
@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTiiiiaaOOOO&&@@@@OO@@NNPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@&&TTTTTTPPTTTTTTNN@@@@@@TTTTTTOOTTTTTT&&@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTTTTTTTTTTTOO@@@@@@OOTTTTTTOOTTTTOO@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTPPTTTTTTTT&&@@@@@@TTTTTT&&TTTTTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@&&TTTTTTTTTTaa@@@@@@@@@@TTTTTTTTTTTTTTOO@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTT&&TTTTTT@@@@@@@@TTTTTTPPiiTTTTTT
@@@@@@@@@@@@@@@@@@TTTTTTTTTTOOTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTiiiiTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTOOiiOOiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&TTTTTTOOTTTTTT&&@@@@@@TTTTTTOOTTTTTT&&@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTPPTTTTTTTTOO@@@@@@OOTTTTTTOOTTTTOO@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTOOTTTTTTTT&&@@@@@@TTTTTT&&TTTTTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@&&TTTTTTTTTT&&@@@@@@@@@@iiTTTTTTTTTTTTOO@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTTOOTTTTii@@@@@@@@TTTTTTOOTTTTTTTT
@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaTTTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTOOiiOOiiTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&&TTTTTT&&TTTTTT&&@@@@@@TTTTTTOOTTTTTT&&@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTOOTTTTTTTTOO@@@@@@OOTTTTTTOOTTTTOO@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTTNNiiTTTTTT&&@@@@@@TTTTTT@@iiTTTTTTOO@@@@@@iiTTTTiiOOTTTTTT@@@@@@@@&&TTTTTTTTTTOO@@@@@@@@88TTTTiiNNPPTTTTPP@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTOOTTTTii@@@@@@OOTTTTTTOOTTTTTT@@@@@@@@TTTTTTOOTTTTTTTT
@@@@@@@@@@@@@@@@@@@@NNTTTTTTOOTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTOOTTOOTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@UUTTTTTTaaTTTTTTNN@@@@@@TTTTTTOOTTTTTTUU@@@@@@iiTTTTOO@@@@@@iiTTTTOO@@@@@@@@@@@@iiTTTTOOPPTTTTTTOO@@@@@@OOTTTTTTPPTTTTOO@@@@@@OOTTTTii@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTT@@TTTTTTTT&&@@@@@@TTTTTT@@77TTTTTTOO@@@@@@PPTTTTTTaaTTTTii@@@@@@@@@@TTTTTTTTTT&&@@@@@@@@&&TTTTii@@OOTTTTii@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTeeTTTTii@@@@@@OOTTTTTT&&TTTTTTUU@@@@@@iiTTTTPPTTTTTTTT
@@@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPiiTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTOOTTiiTTTTTTTTTTTTTTTTTTNN@@NNTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTTTT@@@@@@@@iiTTTTiiTTTTii@@@@@@@@iiTTTTOO@@@@@@iiTTTTTTTTTT&&@@@@@@iiTTTTOOOOTTTTTTOO@@@@@@&&TTTTTTTTTTTTOO@@@@@@OOTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTT@@PPTTTTTT&&@@@@@@TTTTTT@@OOTTTTTTOO@@@@@@&&TTTTTTTTTTTT&&@@@@@@@@@@TTTTTTTTTTNN@@@@@@@@&&TTTTii@@OOTTTTTT@@@@@@@@@@&&TTTTTT@@@@@@@@@@OOTTTTTTTTTTTTaa@@@@@@OOTTTTTTWWTTTTTT&&@@@@@@OOTTTTTTTTTTTTii
@@@@@@@@@@@@@@@@@@@@@@@@PPOOTTNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTffTTTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTT&&TTTTTTTTTTTTTTTTNN@@NNTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@aaTTTTTTTTiiOO@@@@@@@@NNTTTTTTTTiiPP@@@@@@@@iiTTTTOO@@@@@@iiTTTTTTTTTTOO@@@@@@iiTTTTOONNTTTTTTOO@@@@@@@@TTTTTTTTTTaa@@@@@@@@OOTTTTTTTTTTTT@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTOO@@@@@@iiTTTT@@OOTTTTTT&&@@@@@@TTTTTT@@OOTTTTTTOO@@@@@@NNTTTTTTTTTT77NN@@@@@@@@@@TTTTTTTTTT@@@@@@@@@@VVTTTTii@@&&TTTTTT@@@@@@@@@@&&TTTTTT@@@@@@@@@@@@TTTTTTTTTTiiNN@@@@@@OOTTTTTT@@TTTTTT&&@@@@@@NNTTTTTTTTTT77@@
@@@@@@@@@@@@@@@@@@@@@@@@@@NNNN@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPiiTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOTTOOTTTTTTTTTTNN@@NNNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNOO&&OONN@@@@@@@@@@@@@@OO&&&&NN@@@@@@@@@@&&&&&&NN@@@@@@OO&&&&&&&&&&NN@@@@@@88&&&&NN@@&&&&&&NN@@@@@@@@@@UUOO&&UU@@@@@@@@@@NN&&&&&&&&&&&&@@@@@@@@@@@@@@@@@@@@@@@@&&&&&&NN@@@@@@&&&&&&@@NN&&&&&&NN@@@@@@OO&&&&@@@@&&&&&&NN@@@@@@@@@@&&&&&&OO@@@@@@@@@@@@@@&&&&&&&&&&@@@@@@@@@@&&&&&&&&@@NN&&&&&&NN@@@@@@@@NN&&&&&&@@@@@@@@@@@@@@OO&&&&OO@@@@@@@@@@NN&&&&&&@@OOOOOONN@@@@@@@@@@&&OOOO&&@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaTTTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOOiiOOiiTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@PPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaTTTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaiiTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTaaTTTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPffTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPTTTTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPP@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT77TTTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPNN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPiiTT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNOOTTTTTTTTTTTTTTTTTTTTTTTTTTTT&&TT@@@@TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPPOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OOOOTTTTTTTTTTTTTTTTTTTTTTTTaa@@@@TTTTTTTTTTTTTTTTTTTTTTTTPPOONN@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@NNOOPPTTTTTTTTTTTTTTTTPP@@@@TTTTTTTTTTTTTTTTPPOOOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@TTTTTTTTTTTT@@@@TTTTTTTTTTOO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
*/
#pragma GCC optimize "-O3"
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <cstdio>
#include <numeric>
#include <cstring>
#include <ctime>
#include <cstdlib>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <list>
#include <cmath>
#include <bitset>
#include <cassert>
#include <queue>
#include <stack>
#include <deque>
    
     
     
using namespace std;
template<typename T1, typename T2>inline void chkmin(T1 &x, T2 y) { if (x > y) x = y; }
template<typename T1, typename T2>inline void chkmax(T1 &x, T2 y) { if (x < y) x = y; }
/** Interface */
     
inline int readChar();
template <class T = int> inline T readInt(); 
template <class T> inline void writeInt( T x, char end = 0 );
inline void writeChar( int x ); 
inline void writeWord( const char *s );
     
/** Read */
     
static const int buf_size = 4096;
     
inline int getChar() {
    static char buf[buf_size];
    static int len = 0, pos = 0;
    if (pos == len) {
        pos = 0, len = fread(buf, 1, buf_size, stdin);
    }
    if (pos == len) {
        return -1;
    }
    return buf[pos++];
}
     
inline int readChar() {
    int c = getChar();
    while (c <= 32) {
        c = getChar();
    }
    return c;
}
     
template <class T>
inline T readInt() {
    int s = 1, c = readChar();
    T x = 0;
    if (c == '-')
        s = -1, c = getChar();
    while ('0' <= c && c <= '9')
        x = x * 10 + c - '0', c = getChar();
    return s == 1 ? x : -x;
}
     
/** Write */
     
static int write_pos = 0;
static char write_buf[buf_size];
     
inline void writeChar( int x ) {
    if (write_pos == buf_size)
        fwrite(write_buf, 1, buf_size, stdout), write_pos = 0;
    write_buf[write_pos++] = x;
}
     
template <class T> 
inline void writeInt( T x, char end ) {
    if (x < 0)
        writeChar('-'), x = -x;
     
    char s[24];
    int n = 0;
    while (x || !n)
        s[n++] = '0' + x % 10, x /= 10;
    while (n--)
        writeChar(s[n]);
    if (end)
        writeChar(end);
}
     
inline void writeWord( const char *s ) {     while (*s)
writeChar(*s++); }
     
struct Flusher {
    ~Flusher() {
        if (write_pos)
            fwrite(write_buf, 1, write_pos, stdout), write_pos = 0;
    }
} flusher;   
#define sz(c) (int)(c).size()
#define all(c) (c).begin(), (c).end()
#define rall(c) (c).rbegin(), (c).rend()
#define left left228
#define right right228
#define next next228
#define rank rank228
#define prev prev228
#define y1 y1228                                                         
#define read(FILENAME) freopen((FILENAME + ".in").c_str(), "r", stdin)
#define write(FILENAME) freopen((FILENAME + ".out").c_str(), "w", stdout)
#define files(FILENAME) read(FILENAME), write(FILENAME)
#define pb push_back
const string FILENAME = "input";


int main() {
	string s;
	cin >> s;
	int pos = -1;
	int keks = 0;
	for (auto c: s) {
		if (c == '1') {
			pos = keks;
			break;
		}
		keks++;
	}
	if (pos == -1) {
		cout << "no" << endl;
	} else {
		int cnt = 0;
		for (int i = keks + 1; i < sz(s); i++) {
			if (s[i] == '0') {
				cnt++;
			}
		}
		if (cnt < 6) {
			cout << "no" << endl;
		} else {
			cout << "yes" << endl;
		}
	}
}