#include <bits/stdc++.h>

using namespace std;

int n,nn=0,sqn=447,a[200069],fq[200069],ps[200069],vl[400469],ls[469][2],bg[200069],ex[469],od[200069],fq2[469],fh[469],lz[469],sq[200069];

int main()
{
	int i,j,r,ii,u,k,mx=0,p,z=0;
	
	scanf("%d",&n);
	for(i=1;i<=n;i++)
	{
		scanf("%d",a+i);
		fq[a[i]]++;
		if(fq[a[i]]>mx)
		{
			bg[i]=a[i];
			mx=fq[a[i]];
		}
		else
		{
			bg[i]=bg[i-1];
		}
		sq[i]=n+1;
	}
	for(i=1;i<=n;i++)
	{
		ps[i]=ps[i-1]+fq[i];
		if(fq[i]>=sqn)
		{
			nn++;
			ex[nn]=i;
			od[i]=nn;
		}
		fq[i]=0;
	}
	for(i=1;i<=n;i++)
	{
		fq[a[i]]++;
		vl[ps[a[i]-1]+fq[a[i]]]=i;
	}
	for(i=1;i<=n;i++)
	{
		fq[i]=0;
	}
	for(i=1;i<=n;i++)
	{
		fq[a[i]]++;
		for(j=1;j<=min(sqn,fq[a[i]]);j++)
		{
			k=vl[ps[a[i]-1]+fq[a[i]]+1-j];
			for(ii=0;ii<2;ii++)
			{
				if(a[ls[j][ii]]==a[i])
				{
					for(r=ii;r<1;r++)
					{
						ls[j][r]=ls[j][r+1];
					}
					ls[j][1]=0;
					break;
				}
			}
			for(ii=0;ii<2;ii++)
			{
				if(k>ls[j][ii])
				{
					for(r=1;r>ii;r--)
					{
						ls[j][r]=ls[j][r-1];
					}
					ls[j][ii]=k;
					break;
				}
			}
		}
		for(j=1;j<sqn;j++)
		{
			if(ls[j][1]>ls[j+1][0])
			{
				z=max(z,i-ls[j+1][0]);
			}
		}
	}
	for(i=1;i<=nn-i;i++)
	{
		for(j=1;j<=nn;j++)
		{
			fq2[j]=fq[ex[j]]+fq[ex[(j+i-1)%nn+1]];
			ps[j]=ps[j-1]+1+fq2[j];
			fh[j]=0;
			lz[j]=0;
		}
		for(j=1;j<=n;j++)
		{
			if(od[a[j]])
			{
				for(ii=0;ii<2;ii++)
				{
					u=!ii*2-1;
					p=(od[a[j]]+nn-i*ii-1)%nn+1;
					lz[p]+=u;
					fh[p]=max(fh[p],lz[p]);
				}
			}
		}
		for(j=1;j<=ps[nn];j++)
		{
			vl[j]=n+1;
		}
		for(j=1;j<=nn;j++)
		{
			lz[j]=0;
			vl[ps[j-1]+1+fh[j]]=0;
		}
		for(j=1;j<=n;j++)
		{
			if(od[a[j]])
			{
				for(ii=0;ii<2;ii++)
				{
					u=!ii*2-1;
					p=(od[a[j]]+nn-i*ii-1)%nn+1;
					lz[p]+=u;
					k=ps[p-1]+1+fh[p]-lz[p];
					vl[k]=min(vl[k],j);
				}
			}
			if(od[bg[j]])
			{
				for(ii=0;ii<2;ii++)
				{
					p=(od[bg[j]]+nn-i*ii-1)%nn+1;
					sq[j]=min(sq[j],vl[ps[p-1]+1+fh[p]-lz[p]]);
				}
			}
		}
	}
	for(i=1;i<=n;i++)
	{
		z=max(z,i-sq[i]);
	}
	printf("%d\n",z);
}