import java.util.InputMismatchException;
import java.math.BigInteger;
import java.io.*;

/**
 * Generated by Contest helper plug-in
 * Actual solution is at the bottom
 */
public class Main {
	public static void main(String[] args) {
		InputReader in = new StreamInputReader(System.in);
		PrintWriter out = new PrintWriter(System.out);
		run(in, out);
	}

	public static void run(InputReader in, PrintWriter out) {
		Solver solver = new TaskD();
		solver.solve(1, in, out);
		Exit.exit(in, out);
	}
}

abstract class InputReader {
	private boolean finished = false;

	public abstract int read();

	public int readInt() {
		int c = read();
		while (isSpaceChar(c))
			c = read();
		int sgn = 1;
		if (c == '-') {
			sgn = -1;
			c = read();
		}
		int res = 0;
		do {
			if (c < '0' || c > '9')
				throw new InputMismatchException();
			res *= 10;
			res += c - '0';
			c = read();
		} while (!isSpaceChar(c));
		return res * sgn;
	}

	public String readString() {
		int c = read();
		while (isSpaceChar(c))
			c = read();
		StringBuffer res = new StringBuffer();
		do {
			res.appendCodePoint(c);
			c = read();
		} while (!isSpaceChar(c));
		return res.toString();
	}

	private boolean isSpaceChar(int c) {
		return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
	}

	public char readCharacter() {
		int c = read();
		while (isSpaceChar(c))
			c = read();
		return (char) c;
	}

	public char[][] readTable(int rowCount, int columnCount) {
		char[][] table = new char[rowCount][columnCount];
		for (int i = 0; i < rowCount; i++) {
			for (int j = 0; j < columnCount; j++)
				table[i][j] = readCharacter();
		}
		return table;
	}

	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public abstract void close();

	}

class StreamInputReader extends InputReader {
	private InputStream stream;
	private byte[] buf = new byte[1024];
	private int curChar, numChars;

	public StreamInputReader(InputStream stream) {
		this.stream = stream;
	}

	public int read() {
		if (numChars == -1)
			throw new InputMismatchException();
		if (curChar >= numChars) {
			curChar = 0;
			try {
				numChars = stream.read(buf);
			} catch (IOException e) {
				throw new InputMismatchException();
			}
			if (numChars <= 0)
				return -1;
		}
		return buf[curChar++];
	}

	@Override
	public void close() {
		try {
			stream.close();
		} catch (IOException ignored) {
		}
	}
}

class Exit {
	private Exit() {
	}

	public static void exit(InputReader in, PrintWriter out) {
		in.setFinished(true);
		in.close();
		out.close();
	}
}

interface Solver {
	public void solve(int testNumber, InputReader in, PrintWriter out);
}

class TaskD implements Solver {
	private char[][][] horizontal = {
		{
			{'.', '.', '.'},
			{'.', '.', '.'},
			{'.', '.', '.'},
		},
		{
			{'.', '.', '.'},
			{'.', 'O', '.'},
			{'.', '.', '.'},
		},
		{
			{'O', '.', '.'},
			{'.', '.', '.'},
			{'.', '.', 'O'},
		},
		{
			{'O', '.', '.'},
			{'.', 'O', '.'},
			{'.', '.', 'O'},
		},
		{
			{'O', '.', 'O'},
			{'.', '.', '.'},
			{'O', '.', 'O'},
		},
		{
			{'O', '.', 'O'},
			{'.', 'O', '.'},
			{'O', '.', 'O'},
		},
		{
			{'O', 'O', 'O'},
			{'.', '.', '.'},
			{'O', 'O', 'O'},
		},
	};

	private char[][][] vertical = {
		{
			{'.', '.', '.'},
			{'.', '.', '.'},
			{'.', '.', '.'},
		},
		{
			{'.', '.', '.'},
			{'.', 'O', '.'},
			{'.', '.', '.'},
		},
		{
			{'.', '.', 'O'},
			{'.', '.', '.'},
			{'O', '.', '.'},
		},
		{
			{'.', '.', 'O'},
			{'.', 'O', '.'},
			{'O', '.', '.'},
		},
		{
			{'O', '.', 'O'},
			{'.', '.', '.'},
			{'O', '.', 'O'},
		},
		{
			{'O', '.', 'O'},
			{'.', 'O', '.'},
			{'O', '.', 'O'},
		},
		{
			{'O', '.', 'O'},
			{'O', '.', 'O'},
			{'O', '.', 'O'},
		},
	};
	private static final long MOD = 1000000007;

	public void solve(int testNumber, InputReader in, PrintWriter out) {
		int rowCount = in.readInt();
		int columnCount = in.readInt();
		char[][] table = in.readTable(4 * rowCount + 1, 4 * columnCount + 1);
		int[][] type = new int[rowCount][columnCount];
		for (int i = 0; i < rowCount; i++) {
			for (int j = 0; j < columnCount; j++) {
				for (char[][] domino : vertical) {
					boolean valid = true;
					for (int k = 0; k < 3; k++) {
						for (int l = 0; l < 3; l++) {
							if (table[4 * i + 1 + k] [4 * j + 1 + l] != domino[k][l])
								valid = false;
						}
					}
					if (valid)
						type[i][j]++;
				}
				for (char[][] domino : horizontal) {
					boolean valid = true;
					for (int k = 0; k < 3; k++) {
						for (int l = 0; l < 3; l++) {
							if (table[4 * i + 1 + k] [4 * j + 1 + l] != domino[k][l])
								valid = false;
						}
					}
					if (valid)
						type[i][j] += 2;
				}
			}
		}
		long[] answer = new long[columnCount + 1];
		answer[0] = 1;
		for (int i = 0; i < columnCount; i++) {
			boolean isVerticalRow = true;
			for (int j = 0; j < rowCount && isVerticalRow; j++) {
				if (type[j][i] == 2)
					isVerticalRow = false;
			}
			if (isVerticalRow && rowCount % 2 == 0)
				answer[i + 1] = (answer[i + 1] + answer[i]) % MOD;
			if (i == columnCount - 1)
				continue;
			long[] count = new long[2];
			long[] nextCount = new long[2];
			count[0] = 1;
			boolean isSecondRowVertical = true;
			for (int j = 0; j < rowCount && isSecondRowVertical; j++) {
				if (type[j][i + 1] == 2)
					isSecondRowVertical = false;
			}
			for (int j = 0; j < rowCount; j++) {
				nextCount[0] = nextCount[1] = 0;
				if (type[j][i] >= 2 && type[j][i + 1] >= 2)
					nextCount[0] = count[0];
				nextCount[0] += count[1];
				if (j == rowCount - 1) {
					long[] temp = nextCount;
					nextCount = count;
					count = temp;
					continue;
				}
				boolean firstVertical = (type[j][i] & 1) != 0 && (type[j + 1][i] & 1) != 0;
				boolean secondVertical = (type[j][i + 1] & 1) != 0 && (type[j + 1][i + 1] & 1) != 0;
				if (firstVertical && secondVertical)
					nextCount[1] += count[0];
				nextCount[0] %= MOD;
				nextCount[1] %= MOD;
				long[] temp = nextCount;
				nextCount = count;
				count = temp;
			}
			if (isVerticalRow && isSecondRowVertical && rowCount % 2 == 0)
				count[0] = (count[0] + MOD - 1) % MOD;
			answer[i + 2] = (answer[i] * count[0]) % MOD;
		}
		out.println(answer[columnCount]);
	}
}