/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author marX
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>

using namespace std;

class BNotSimplyBeatifulStrings {
public:
    void solve(std::istream& in, std::ostream& out) {
        string s; in >> s;

        map<char,int> f;

        for (auto x : s) {
            f[x]++;
        }

        if (f.size() == 1 || f.size() >= 5) {
            out << "No" << endl;
        } else if (f.size() == 4) {
            out << "Yes" << endl;
        } else if (f.size() == 2) {
            auto a = f.begin()->second;
            auto b = f.rbegin()->second;
            out << (min(a, b) >= 2 ? "Yes" : "No") << endl;
        } else if (f.size() == 3) {
            if (s.length() >= 4) {
                out << "Yes" << endl;
            } else {
                out << "No" << endl;
            }
        } else {
            assert(false);
        }
    }
};


int main() {
	BNotSimplyBeatifulStrings solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}