using namespace std;
#include "bits/stdc++.h"

typedef string::const_iterator State;
#define eps 1e-8L
#define MAX_MOD 1000000007LL
#define GYAKU 500000004LL
#define MOD 998244353LL
#define pb push_back
#define mp make_pair
typedef long long ll;
typedef long double ld;
#define REP(a, b) for (long long(a) = 0; (a) < (b); ++(a))
#define ALL(x) (x).begin(), (x).end()

#define int long long

void solve()
{
    int n;
    cin >> n;
    vector<int> A, B;
    REP(i, n)
    {
        int c;
        cin >> c;
        A.push_back(c);
    }
    REP(i, n)
    {
        int c;
        cin >> c;
        B.push_back(c);
    }

    vector<int> count(n + 1, 0);
    int itr = n - 1;
    for (int i = n - 1; i >= 0; --i)
    {
        if (B[i] == A[itr])
        {
            // Just OK.
            itr--;
        }
        else
        {
            if (i != n - 1 and B[i] == B[i + 1])
            {
                count[B[i]]++;
            }
            else
            {
                while (count[A[itr]] > 0 and A[itr] != B[i])
                {
                    count[A[itr]]--;
                    itr--;
                }
                if (A[itr] != B[i])
                {
                    cout << "NO" << endl;
                    return;
                }
                itr--;
            }
        }
    }
    sort(ALL(A));
    sort(ALL(B));
    if (A != B)
    {
        cout << "NO" << endl;
    }
    else
    {
        cout << "YES" << endl;
    }
}
#undef int

// generated by oj-template v4.7.2
// (https://github.com/online-judge-tools/template-generator)
int main()
{
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout << fixed << setprecision(100);
    int t = 1;
    cin >> t; // comment out if solving multi testcase
    for (int testCase = 1; testCase <= t; ++testCase)
    {
        solve();
    }
    return 0;
}